import type { StepList } from './types'

const steps: Record<string, StepList> = {
  'Kylling i pita': [
    ['Skjær opp', 'Skjær kyllingfileten i terninger på ca. 1 cm. Skjær paprikaene i biter og vårløken i ringer.'],
    ['Stek kyllingen', 'Varm olje i en panne på middels varme og stek kyllingen til den begynner å få farge. Tilsett paprika og vårløk.'],
    ['Krydre', 'Strø over tikka masala-krydderet og rør godt. Tilsett yoghurten, bland og varm gjennom. Smak til med salt og pepper.'],
    ['Varm pitabrødene', 'Varm pitabrødene etter anvisningen på pakken.'],
    ['Fyll og server', 'Fyll pitabrødene med kyllingblandingen og crispisalat, og server med en gang.'],
  ],
  'Kyllingfilet med ris og salat': [
    ['Sett på ris', 'Kok risen etter anvisningen på pakken.'],
    ['Stek kyllingen', 'Krydre kyllingfileten med salt og pepper og stek den gjennom i en panne, ca. 5–6 minutter på hver side.'],
    ['Lag sausen', 'Lag kyllingsausen etter beskrivelsen på pakken.'],
    ['Lag salaten', 'Skjær salat og paprika og bland med maisen.'],
    ['Server', 'Skjær kyllingen i skiver og server med ris, saus og salat.'],
  ],
  'Kyllingfilet med rotgrønnsaker': [
    ['Sett ovnen på', 'Sett ovnen på 225 °C.'],
    ['Forbered rotgrønnsakene', 'Skrell kålrot, gulrot, sellerirot og persillerot og skjær dem i tykke staver. Vend dem i olje sammen med parmesan og oregano, og krydre med salt og pepper. Legg dem i en ildfast form.'],
    ['Stek grønnsakene', 'Stek grønnsakene midt i ovnen i 20–25 minutter.'],
    ['Brun kyllingen', 'Brun kyllingfiletene i olje eller smør, ca. 2 minutter på hver side. Krydre med salt og pepper.'],
    ['Stek ferdig', 'Legg kyllingen oppå grønnsakene og sett formen tilbake i ovnen i ca. 15–18 minutter, til kyllingen er gjennomstekt (70 °C inni).'],
    ['Server', 'Server med finhakket vårløk over, og gjerne brød eller rømme.'],
  ],
  'Kyllingklubber og ris': [
    ['Sett ovnen på', 'Sett ovnen på 200 °C.'],
    ['Krydre og stek', 'Legg kyllingklubbene på en stekeplate med bakepapir og krydre dem med salt, pepper og paprikapulver. Stek i ca. 35–45 minutter, til de er gyllene og gjennomstekte.'],
    ['Kok ris', 'Kok risen etter anvisningen på pakken.'],
    ['Lag salat', 'Vask og skjær salaten.'],
    ['Server', 'Server klubbene med ris og salat.'],
  ],
  'Kyllinglår i form': [
    ['Sett ovnen på', 'Sett ovnen på 200 °C.'],
    ['Skjær grønnsakene', 'Del tomatene i biter og skjær gulrøttene i skiver. Skyll kikertene.'],
    ['Legg i formen', 'Legg kikerter, gulrot og tomater i en ildfast form. Legg kyllinglårene oppå og krydre dem godt med salt og pepper.'],
    ['Stek', 'Stek i ca. 40–50 minutter, til kyllingen er gyllen og gjennomstekt.'],
    ['Kok ris', 'Kok risen mens kyllingen står i ovnen.'],
    ['Server', 'Server kyllinglårene med grønnsaker og ris.'],
  ],
  Kålstuing: [
    ['Skjær kålen', 'Del kålen i båter og fjern kjernen.'],
    ['Kok kålen', 'Legg kålen i en kjele med litt vann og salt og kok den under lokk til den er mør.'],
    ['Smak til', 'Smak til med salt og pepper. Tykk gjerne med litt mel utrørt i kaldt vann om du vil ha en tykkere stuing.'],
    ['Server', 'Server stuingen varm med poteter eller brød.'],
  ],
  'Laks og spagetti': [
    ['Kok spagetti', 'Kok spagettien etter anvisningen på pakken. Ta vare på litt av kokevannet og sil av.'],
    ['Stek bacon og løk', 'Skjær bacon og løk i små biter og stek dem gylne i en panne.'],
    ['Stek laksen', 'Stek laksen i en annen panne, ca. 3–4 minutter på hver side. Del den i biter.'],
    ['Lag sausen', 'Rør sammen egg og matfløte. Ta pannen med bacon og løk av varmen og rør inn eggeblandingen med litt kokevann, slik at det blir en kremet saus.'],
    ['Bland', 'Vend spagettien inn i sausen og legg laksebitene forsiktig oppå.'],
    ['Server', 'Server med en gang.'],
  ],
  Lakseburger: [
    ['Stek burgerne', 'Stek lakseburgerne etter anvisningen på pakken, til de er gjennomvarme.'],
    ['Varm brødene', 'Varm hamburgerbrødene kort i ovnen eller i en tørr panne.'],
    ['Sett sammen', 'Legg salat og lakseburger i brødet og legg på tilbehøret til lakseburgeren.'],
  ],
  Laksetaco: [
    ['Krydre laksen', 'Skjær laksen i biter og vend dem i tacokrydder.'],
    ['Stek laksen', 'Stek laksen i en panne til den er gjennomstekt, ca. 3–4 minutter. Del den forsiktig i mindre biter.'],
    ['Skjær tilbehør', 'Skjær salat, paprika og ananas i små biter og sil av maisen.'],
    ['Varm tacoen', 'Varm tacoskjell eller tacolefser etter anvisningen på pakken.'],
    ['Server', 'Fyll tacoen med laks, salat, paprika, mais og ananas, og topp med tacosaus.'],
  ],
  Laksewok: [
    ['Kok nudler', 'Kok nudlene etter anvisningen på pakken og sil av.'],
    ['Skjær opp', 'Skjær laksen i terninger og gulroten i tynne staver.'],
    ['Stek laksen', 'Stek laksen raskt i en varm wok eller panne til den har fått farge. Ta den ut.'],
    ['Wok gulroten', 'Wok gulrotstavene i noen minutter til de er møre men fortsatt sprø.'],
    ['Bland sammen', 'Ha nudlene og laksen tilbake i woken, tilsett sweet chilli-saus og vend forsiktig sammen til alt er varmt.'],
    ['Server', 'Server med en gang.'],
  ],
  'Laksewok v2': [
    ['Marinér laksen', 'Skjær laksen i terninger og bland med soyasaus, limesaft og litt revet ingefær. La den stå i minst 10 minutter.'],
    ['Kok ris', 'Kok risen etter anvisningen på pakken.'],
    ['Skjær grønnsakene', 'Hakk vårløk, skjær paprika og sopp, skjær rødløk i skiver og finhakk hvitløk.'],
    ['Stek laksen', 'Brun laksen raskt i olje på høy varme til den har fått farge. Krydre med salt og pepper og ta den ut.'],
    ['Wok grønnsakene', 'Stek grønnsakene og bambusskuddene i frisk olje på høy varme i noen minutter, til de er møre men sprø.'],
    ['Lag sausen', 'Rør sammen soyasaus, fiskebuljong og maisenna med resten av marinaden, og hell det over grønnsakene. La det tykne litt.'],
    ['Ferdigstill', 'Legg laksen tilbake i woken og varm den forsiktig gjennom.'],
    ['Server', 'Server woken varm over ris.'],
  ],
  Lammeskank: [
    ['Sett ovnen på', 'Sett ovnen på 150 °C.'],
    ['Brun skankene', 'Brun lammeskankene i en stor gryte sammen med grovhakkede grønnsaker i noen minutter.'],
    ['Lag braisingen', 'Tilsett tomater, rødvin, krydder og vann til skankene nesten er dekket. Legg på lokk.'],
    ['Stek i ovnen', 'Sett gryten i ovnen og la skankene braisere i ca. 4 timer, til kjøttet faller fra beinet.'],
    ['Lag saus', 'Sil væsken over i en vid panne og kok den inn til en tredel. Sil den én gang til og smak til med salt.'],
    ['Lag potetpuré', 'Skrell og del poteter, kok dem møre og la dem dampe tørre. Mos dem med fløte, smør og litt salt.'],
    ['Server', 'Server skankene med saus, gjerne ovnsbakte rotgrønnsaker og potetpuré.'],
  ],
  'Lapskaus på boks': [
    ['Varm lapskausen', 'Hell lapskausen fra boksen i en kjele og varm den opp under omrøring, til den er kokende varm.'],
    ['Smak til', 'Smak til med salt og pepper om det trengs.'],
    ['Server', 'Server lapskausen med flatbrød.'],
  ],
  Lasagne: [
    ['Sett ovnen på', 'Sett ovnen på temperaturen som står på Toro-pakken.'],
    ['Stek kjøttdeigen', 'Brun kjøttdeigen i en panne til den er gjennomstekt og smuldrer.'],
    ['Lag lasagnen', 'Følg anvisningen på Toro-pakken: bland kjøttdeig, melk og pakkens innhold, og legg lasagne og saus lagvis i en ildfast form.'],
    ['Stek', 'Sett formen i ovnen og stek etter anvisningen, vanligvis ca. 30–40 minutter.'],
    ['Lag salaten', 'Skjær salat og paprika og bland med maisen.'],
    ['Server', 'La lasagnen stå noen minutter før servering, og server med salaten.'],
  ],
  Nachos: [
    ['Sett ovnen på', 'Sett ovnen på 200 °C.'],
    ['Lag kjøttsausen', 'Fres kjøttdeigen og finhakket rødløk i en varm panne. Tilsett tacokrydder, vann og de brune bønnene. La sausen småkoke i 5 minutter.'],
    ['Legg lagvis', 'Legg tortillachips i en ildfast form, fordel kjøttsausen over, og strø over revet ost.'],
    ['Stek', 'Stek i ovnen i ca. 5–10 minutter, til osten er smeltet.'],
    ['Server', 'Server med avokado i biter og salsa.'],
  ],
  'Nakkekoteletter med gratinert brokkoli og purre': [
    ['Sett ovnen på', 'Sett ovnen på 225 °C.'],
    ['Kok grønnsakene', 'Del brokkolien i buketter og skjær purren i biter. Kok dem i lettsaltet vann i ca. 4 minutter og sil av. Legg dem i en ildfast form.'],
    ['Lag toppingen', 'Riv parmesan og skallet av sitronen. Bland med litt sitronsaft, smør og brødsmuler, og smak til med salt og pepper.'],
    ['Gratiner', 'Fordel toppingen over grønnsakene og gratiner i ovnen i ca. 15 minutter.'],
    ['Stek kotelettene', 'Krydre nakkekotelettene med salt og pepper og stek dem i olje, 3–4 minutter på hver side.'],
    ['Kok ris', 'Kok risen etter anvisningen på pakken.'],
    ['Server', 'Server kotelettene med gratinert brokkoli og purre, og ris.'],
  ],
  'Ovnsbakt torsk': [
    ['Sett ovnen på', 'Sett ovnen på 180 °C.'],
    ['Forbered fisken', 'Del torskefileten i serveringsstykker.'],
    ['Forkok grønnsakene', 'Skjær purre, gulrot og selleri i biter. Bland en fisk-saus etter anvisningen på pakken. Kok grønnsakene 2 minutter i kokende vann og sil av.'],
    ['Legg i form', 'Legg grønnsakene i en smurt ildfast form og legg fisken oppå. Krydre med salt, pepper og timian.'],
    ['Saus og ost', 'Hell sausen over og strø revet ost på toppen. Legg gjerne cherrytomater rundt.'],
    ['Stek', 'Stek i ca. 15 minutter, til fisken er gjennomstekt og osten er gyllen.'],
    ['Server', 'Server med ris eller poteter.'],
  ],
  'Pad thai': [
    ['Bløtlegg nudlene', 'Bløtlegg eller kok nudlene etter anvisningen på pakken og sil av.'],
    ['Skjær opp', 'Skjær kjøttet i tynne strimler, gulrot og paprika i staver, rødløk i skiver og vårløk i ringer. Hakk peanøttene grovt.'],
    ['Lag sausen', 'Bland fiskesaus, sweet chilli-saus og østerssaus.'],
    ['Stek kjøttet', 'Stek kyllingen eller svinekjøttet i en varm wok til det er gjennomstekt. Ta det ut.'],
    ['Wok grønnsakene', 'Wok gulrot, paprika, rødløk og bambusskudd raskt i olje. Skyv dem til siden og ha i eggene. La dem stivne og rør dem løst sammen.'],
    ['Bland sammen', 'Ha nudler, kjøtt og sausen i woken og vend alt sammen på høy varme. Tilsett bønnespirer helt til slutt.'],
    ['Server', 'Server med peanøtter, vårløk og en skive lime.'],
  ],
  Pannekaker: [
    ['Lag røren', 'Visp mel og egg med litt av melken til en klumpfri røre. Tilsett resten av melken litt om gangen, og en klype salt. La den svelle en stund.'],
    ['Stek baconet', 'Stek baconet sprøtt i en panne og la det renne av på tørkepapir.'],
    ['Stek pannekakene', 'Varm smør i en panne på middels varme og stek tynne pannekaker, 1–2 minutter på hver side, til de er gylne.'],
    ['Server', 'Fyll pannekakene med bacon, syltetøy eller sukker.'],
  ],
  'Pasta bolognese': [
    ['Kok spagetti', 'Kok spagettien etter anvisningen på pakken og sil av.'],
    ['Stek løk og kjøttdeig', 'Finhakk løken og fres den myk. Ha i kjøttdeigen og brun den til den smuldrer.'],
    ['Lag sausen', 'Hell i spagettisausen og la det småkoke i 15–20 minutter. Smak til med salt og pepper.'],
    ['Server', 'Server sausen over spagettien, gjerne med revet ost.'],
  ],
  'Pasta carbonara': [
    ['Kok pasta', 'Kok pastaen etter anvisningen. Ta vare på litt kokevann og sil av.'],
    ['Stek bacon og løk', 'Skjær bacon og sjalottløk i små biter og stek dem gylne i en panne. Ha i skinken fra boksen og varm den gjennom.'],
    ['Kok erter', 'Kok ertene kort i lettsaltet vann og sil av.'],
    ['Lag eggsausen', 'Visp eggeplommer eller hele egg sammen i en bolle.'],
    ['Bland', 'Ta pannen av varmen og vend pastaen inn i baconblandingen. Rør inn eggene og litt kokevann, så de blir en kremet saus uten å stivne. Bland inn ertene.'],
    ['Server', 'Server med en gang, med pepper og gjerne revet ost.'],
  ],
  'Pastasalat m kylling': [
    ['Kok pasta', 'Kok pastaen etter anvisningen, skyll den i kaldt vann og la den renne godt av.'],
    ['Stek kyllingen', 'Stek kyllingen gjennom i en panne og krydre med salt og pepper. La den avkjøles og skjær den i biter.'],
    ['Skjær grønnsakene', 'Skjær paprika og tomater i biter, og vask og riv salaten. Sil av maisen.'],
    ['Bland', 'Bland pasta, kylling og grønnsaker i en stor skål. Tilsett en dressing du liker.'],
    ['Server', 'Server pastasalaten kald eller lunken.'],
  ],
  'Pestolaks i ovn': [
    ['Sett ovnen på', 'Sett ovnen på 200 °C.'],
    ['Forbered grønnsakene', 'Skjær gulrot og løk i biter, legg dem på en stekeplate og vend dem i litt olje. Stek dem i ca. 10 minutter mens du forbereder laksen.'],
    ['Smør på pesto', 'Legg laksen på en form eller stekeplate og smør pesto utover.'],
    ['Stek laksen', 'Stek laksen i ovnen i ca. 12–15 minutter, til den er gjennomstekt.'],
    ['Kok ris', 'Kok risen etter anvisningen på pakken.'],
    ['Server', 'Server laksen med ris og ovnsbakte grønnsaker, og dryss over hakket dill.'],
  ],
}

export default steps
