import type { StepList } from './types'

// Best-effort preparation steps. Recipes with a link are based on the linked recipe (in our own words);
// the rest are guesses from the ingredients and notes. Keyed by recipe name.
const steps: Record<string, StepList> = {
  'Al forno (som betyr "bakt")': [
    ['Gjør klart', 'Sett ovnen på 180 °C. Ha vann på kok i en stor kjele og finhakk løken.'],
    ['Kok pasta', 'Kok pastaen ca. 1 minutt kortere enn det som står på pakken, så den ikke blir myk i ovnen. Sil av.'],
    ['Lag fyllet', 'Fres løken mykt i en panne. Ha i skinken fra boksen og bland inn al forno-sausen eller -blandingen etter anvisningen.'],
    ['Bland og legg i form', 'Vend pasta og saus sammen og legg alt i en ildfast form.'],
    ['Dryss ost', 'Strø revet ost tykt utover.'],
    ['Stek', 'Sett formen i ovnen i ca. 15 minutter, til osten er smeltet og gyllen. La stå et par minutter før servering.'],
  ],
  Andebryst: [
    ['Krydre og pakk', 'Ta andebrystet ut av kjøleskapet en halvtime i forveien. Salt og pepre, og vakuumpakk det.'],
    ['Sous vide', 'Legg posen i vannbad på 58 °C i 2 timer.'],
    ['Tørk og ripe', 'Ta brystet ut av posen og tørk det godt. Ripe skinnet i rutemønster uten å skjære inn i kjøttet.'],
    ['Stek skinnet', 'Legg brystet med skinnsiden ned i en kald, tørr panne og sett på middels varme. Stek 4–6 minutter til skinnet er gyllent og sprøtt.'],
    ['Snu og hvil', 'Snu og stek kjøttsiden ca. 30 sekunder. La kjøttet hvile 5 minutter før du skjærer det i tynne skiver.'],
  ],
  Betasuppe: [
    ['Kok kjøttet', 'Legg svineknoken i en stor kjele med kaldt vann. Kok opp, øs av skummet, og la den småkoke ca. 1,5–2 timer til kjøttet begynner å slippe beinet.'],
    ['Skjær grønnsaker', 'Skrell og skjær poteter, gulrot, kålrot og sellerirot i terninger. Del purre og løk i biter.'],
    ['Kok grønnsakene', 'Ha grønnsakene i kjelen og la det småkoke i ca. 20–25 minutter, til alt er mørt.'],
    ['Ta kjøttet av beinet', 'Ta opp knoken, plukk kjøttet av beinet og skjær det i biter. Legg kjøttet tilbake i suppen.'],
    ['Smak til', 'Smak til med salt og pepper.'],
    ['Server', 'Server suppen varm med flatbrød til.'],
  ],
  'Biff og grønnsakswok': [
    ['Lag buljongblandingen', 'Bland revet ingefær, revet appelsinskall, finhakket hvitløk, kjøttbuljong og soyasaus i en kopp.'],
    ['Skjær grønnsakene', 'Skjær paprika i biter, del vårløk i tynne skiver, del gulrot og sellerirot i tynne staver og skjær sjampinjongene i skiver. Sil av bønnespirene.'],
    ['Stek kjøttet', 'Skjær biffen i strimler. Varm oljen i wokpannen på sterk varme og brun kjøttet 3–5 minutter. Ta det ut på en tallerken.'],
    ['Wok grønnsakene', 'Ha paprika, vårløk, gulrot, sellerirot og sopp i woken. Hell over buljongblandingen og wok 3–4 minutter.'],
    ['Kok nudlene', 'Kok nudlene etter anvisningen på pakken, slik at de blir ferdige samtidig.'],
    ['Bland sammen', 'Ha bønnespirene og kjøttet tilbake i woken, og varm gjennom 2–3 minutter under omrøring.'],
    ['Server', 'Server woken over nudlene.'],
  ],
  'Biff stroganoff': [
    ['Brun kjøttet', 'Skjær biffen i tynne strimler. Brun den i omganger i olje og smør i en stor kjele, til den er gyllen. Sett kjøttet til side.'],
    ['Stek løk og sopp', 'Ha finhakket løk og litt hvitløk i kjelen og stek den myk. Ha i soppen i skiver og stek til den får farge.'],
    ['Lag saus', 'Rør inn tomatpuré og la den ristes litt. Hell i kjøttbuljong og la det småkoke til sausen tykner litt.'],
    ['Ferdigstill', 'Rør inn crème fraîche og ha kjøttet tilbake. Varm gjennom og smak til med salt og pepper.'],
    ['Kok poteter', 'Kok potetene mens du lager stroganoffen, eller stek dem i ovnen.'],
    ['Server', 'Server med poteter, rødbeter og gjerne persille.'],
  ],
  Blomkålsuppe: [
    ['Skjær blomkålen', 'Vask blomkålen og del den i buketter. Finhakk løken.'],
    ['Kok suppen', 'Ha blomkål, løk, vann, hønsebuljong og melk i en kjele. Kok til blomkålen er myk.'],
    ['Blend', 'Ta opp noen buketter til pynt. Bland resten av suppen glatt med en stavmikser, og smak til med salt og pepper.'],
    ['Stek baconet', 'Stek baconet sprøtt i en panne. Ha i vårløk i skiver og la det steke 1 minutt.'],
    ['Server', 'Fordel de reserverte buketene i tallerkenene, hell over suppen og topp med bacon og vårløk. Server med baguette.'],
  ],
  'Butter Chicken': [
    ['Sett på ris', 'Kok risen etter anvisningen på pakken.'],
    ['Stek kyllingen', 'Skjær kyllingfilet i biter og stek dem lett i en panne til de har fått farge.'],
    ['Tilsett sausen', 'Hell i butter chicken-blandingen og la det småkoke til kyllingen er gjennomstekt, ca. 10–15 minutter. Følg anvisningen på glasset.'],
    ['Kok brokkoli', 'Del brokkolien i buketter og kok den 2–3 minutter, til den er mør men fortsatt fast.'],
    ['Server', 'Server kyllingen over ris med brokkoli og mango chutney ved siden av.'],
  ],
  'Chili con carne': [
    ['Sett på ris', 'Kok risen etter anvisningen på pakken.'],
    ['Brun kjøttdeigen', 'Brun kjøttdeigen i en stor kjele til den smuldrer og er gjennomstekt. Ha i hakket paprika og la den mykne litt.'],
    ['Tilsett tomater og bønner', 'Ha i hermetiske tomater og chilibønner (med litt av væsken). Smak til med salt og pepper.'],
    ['La det småkoke', 'La chilien småkoke under lokk i ca. 20–30 minutter, og rør av og til. Tilsett litt vann hvis den blir for tykk.'],
    ['Varm baguettene', 'Stek hvitløksbaguettene i ovnen etter anvisningen på pakken.'],
    ['Server', 'Server chilien over ris, med hvitløksbaguett ved siden av.'],
  ],
  'Ciabatta med kylling': [
    ['Stek kyllingen', 'Krydre kyllingfileten og stek den gjennom i en panne, ca. 5–6 minutter på hver side.'],
    ['Varm brødet', 'Del ciabattaen og varm den kort i ovnen eller i en tørr panne.'],
    ['Legg sammen', 'Skjær kyllingen i skiver og legg den i brødet sammen med det du ellers vil ha: salat, tomat og en god saus.'],
  ],
  Dumplings: [
    ['Lag dippen og skjær grønnsaker', 'Bland hoisinsaus, ketjap manis, sesamfrø og limesaft til dippen. Skjær gulrot og vårløk, og riv salaten.'],
    ['Lag deigen', 'Bland hvetemel og vann til en stiv deig, og elt den glatt. Pakk den inn og la den hvile mens du lager fyllet.'],
    ['Lag fyllet', 'Bland kjøttdeig av svin med finhakket vårløk, chili, hvitløk, bambusskudd, soyasaus og litt sesamolje.'],
    ['Kjevle ut', 'Kjevle ut en tredel av deigen om gangen tynt, ca. 2 mm. Stikk ut sirkler på 6–8 cm og la resten av deigen ligge tildekket.'],
    ['Fyll og brett', 'Legg en teskje fyll på hver sirkel, fukt kanten med vann, brett den sammen og klyp den tett.'],
    ['Stek og damp', 'Brun dumplingsene i olje på middels varme til de er gylne. Ha i ca. 1 dl vann, sett på lokk og la dem dampe til vannet er borte. Stek 2 minutter til uten lokk.'],
    ['Server', 'Server med grønnsaker, hjertesalat og dippen.'],
  ],
  'Entrecote ala Tobias': [
    ['Sett på ris', 'Kok risen etter anvisningen på pakken.'],
    ['Ta frem kjøttet', 'Ta entrecoten ut av kjøleskapet ca. 30 minutter før steking. Tørk den og krydre med salt og pepper.'],
    ['Stek entrecoten', 'Stek den i en veldig varm panne med olje, 2–4 minutter på hver side etter hvor stekt du vil ha den. Tilsett gjerne et par knuste hvitløksfedd og litt smør mot slutten.'],
    ['La den hvile', 'Legg kjøttet under folie og la det hvile 5–10 minutter, så saften blir i kjøttet.'],
    ['Aspargesen og sausen', 'Stek eller kok aspargesen mør, 3–5 minutter. Varm kjøttsausen etter anvisningen.'],
    ['Server', 'Skjær entrecoten i skiver og server med ris, asparges og saus.'],
  ],
  Fajitas: [
    ['Skjær kylling og paprika', 'Skjær kyllingen og paprikaene i strimler.'],
    ['Stek kyllingen', 'Stek kyllingen i en varm panne til den er gyllen og nesten gjennomstekt.'],
    ['Tilsett paprika og krydder', 'Ha i paprikastrimlene og stek 3–4 minutter. Strø over fajitakrydderet og tilsett litt vann etter anvisningen på pakken. La det småkoke et par minutter.'],
    ['Varm lefsene', 'Varm tacolefsene i en tørr panne eller i ovnen.'],
    ['Server', 'Fyll lefsene med kyllingblandingen og server med tilbehør du liker, for eksempel salat, rømme og salsa.'],
  ],
  Falafel: [
    ['Lag falafelmassen', 'Skyll kikertene og tørk dem godt. Kjør dem grovt i en food processor sammen med egg, spisskummen, finhakket chili, hvitløk, potetmel og salt.'],
    ['Form og hvil', 'Form massen til små boller eller flate kaker. La dem hvile litt i kjøleskapet så de holder formen.'],
    ['Stek falafelen', 'Stek falafelen i rikelig med olje på middels varme til den er gyllen og sprø på alle sider, ca. 3–4 minutter på hver side. La den renne av på tørkepapir.'],
    ['Lag yoghurtsausen', 'Bland gresk yoghurt med finhakket hvitløk, hakket dill og en klype salt.'],
    ['Skjær tilbehøret', 'Skjær salat, agurk og rødløk.'],
    ['Server', 'Varm lefsene eller pitabrødene, og fyll dem med falafel, salat, agurk, rødløk og yoghurtsaus.'],
  ],
  'Ferdig fiskegrateng': [
    ['Gjør klart', 'Sett ovnen på temperaturen som står på gratengpakken. Skjær gulroten i skiver.'],
    ['Kok makaroni og gulrot', 'Kok makaroni etter anvisningen, og ha gulrotskivene i vannet de siste minuttene. Sil av.'],
    ['Stek gratengen', 'Sett den ferdige fiskegratengen i ovnen etter anvisningen på pakken, vanligvis 30–40 minutter.'],
    ['Server', 'Server gratengen med makaroni og gulrot ved siden av.'],
  ],
  Finnbiff: [
    ['Tin kjøttet delvis', 'Ta reinsdyrskavet ut av fryseren litt i forveien. Det er lettest å steke når det fortsatt er litt frossent.'],
    ['Stek sopp og bacon', 'Skjær sopp og bacon i biter. Brun dem raskt i smør og legg alt over i en kjele.'],
    ['Brun kjøttet', 'Varm en panne med mer smør og brun kjøttet i omganger på sterk varme. Ha det over i kjelen etter hvert.'],
    ['Lag sausen', 'Tilsett seterrømme, melk, geitost, knuste einebær og timian. La det småkoke ca. 5 minutter, og smak til med salt og pepper.'],
    ['Kok potetene', 'Kok potetene møre mens du lager finnbiffen.'],
    ['Server', 'Server med poteter, og gjerne tyttebærsyltetøy.'],
  ],
  Fiskeburger: [
    ['Stek fiskeburgerne', 'Stek burgerne etter anvisningen på pakken, i panne eller i ovn, til de er gjennomvarme og gylne.'],
    ['Varm brødene', 'Varm hamburgerbrødene kort i ovnen eller i en tørr panne.'],
    ['Sett sammen', 'Legg fiskeburgeren i brødet og legg på ketchup og det tilbehøret du vil ha.'],
  ],
  Fiskegrateng: [
    ['Gjør klart', 'Sett ovnen på 200 °C. Kok pastaen 1–2 minutter kortere enn anvist, og sil av. Skjær gulroten i tynne skiver og skjær fisken i biter.'],
    ['Lag hvit saus', 'Smelt smøret, rør inn melet og la det surre et minutt. Tilsett melken litt om gangen under omrøring til sausen er glatt og tykner. Smak til med salt og pepper.'],
    ['Bland', 'Rør inn halvparten av osten, og la sausen avkjøles litt. Rør inn eggene.'],
    ['Legg i form', 'Legg pasta, gulrot og fisk lagvis i en smurt ildfast form, og hell sausen over.'],
    ['Dryss ost og stek', 'Strø resten av osten over. Stek midt i ovnen i ca. 30 minutter, til gratengen er gyllen og satt.'],
  ],
  'Fiskekaker 🐠': [
    ['Sett på poteter', 'Kok potetstappe eller varm ferdig stappe etter anvisningen. Skrell gulrot og pastinakk, skjær dem i staver og kok dem møre.'],
    ['Stek fiskekakene', 'Stek fiskekakene i smør eller olje på middels varme, ca. 4–5 minutter på hver side, til de er gyllne og gjennomvarme.'],
    ['Server', 'Server fiskekakene med potetstappe, gulrot og pastinakk.'],
  ],
  Fiskepinner: [
    ['Sett på stappen', 'Lag potetstappe eller varm ferdig stappe etter anvisningen. Skrell gulrot og kok den mør.'],
    ['Stek fiskepinnene', 'Stek fiskepinnene i panne eller ovn etter anvisningen på pakken, til de er gylne og sprø.'],
    ['Server', 'Server fiskepinnene med potetstappe, gulrot og ketchup.'],
  ],
  'Fiskepudding i terteskjell': [
    ['Lag hvit saus', 'Smelt smør, rør inn mel og spe med melk litt om gangen til sausen er glatt. Smak til med muskat, salt og hvit pepper, eller bruk ferdig hvit saus.'],
    ['Varm skjellene', 'Sett terteskjellene i ovnen på 150 °C noen minutter så de blir varme.'],
    ['Del fiskepuddingen', 'Skjær fiskepuddingen i biter som passer i skjellene.'],
    ['Kok erter', 'Kok ertene kort i lettsaltet vann og sil av.'],
    ['Bland', 'Vend fiskepudding og erter forsiktig ned i den varme sausen og varm gjennom.'],
    ['Fyll og server', 'Fyll skjellene like før servering. Topp med reker og gjerne litt dill.'],
  ],
  'Fiskesuppe 🐠': [
    ['Lag buljongen', 'Kok opp vann med fiskebuljong i en kjele. Skjær løk og gulrot i små biter.'],
    ['Kok grønnsakene', 'Ha løk og gulrot i buljongen og la det småkoke i ca. 10 minutter. Tilsett en skvett hvitvinseddik og litt revet appelsinskall.'],
    ['Tilsett fløte', 'Hell i fløten og la suppen bli varm igjen uten å koke hardt.'],
    ['Ha i fisken', 'Skjær torsk eller sei i terninger, legg den i suppen og la den trekke 3–4 minutter til den er hvit og gjennomkokt.'],
    ['Reker og spinat', 'Ha i rekene og spinaten helt til slutt og la det varmes gjennom. Smak til med salt og pepper.'],
    ['Server', 'Server suppen varm, gjerne med brød.'],
  ],
}

export default steps
