import type { StepList } from './types'

const steps: Record<string, StepList> = {
  Pinnekjøtt: [
    ['Legg i vann', 'Legg pinnekjøttet i kaldt vann og la det stå til bløtlegging i 24–36 timer (les pakken, saltet pinnekjøtt trenger lenge). Bytt vann et par ganger.'],
    ['Gjør klart', 'Legg risten eller pinner i bunnen av en stor gryte og hell vann under, ca. 2 cm. Ordne kjøttet oppå.'],
    ['Damp', 'Sett på lokk og damp kjøttet på middels varme i ca. 2–2,5 timer, til det faller lett fra beinet. Fyll på litt vann underveis.'],
    ['Kok potetene', 'Skrell potetene og kok dem møre i lettsaltet vann.'],
    ['Varm stappen', 'Varm kålerabistappen (eller lag den selv) og smak til med salt, pepper og litt muskat.'],
    ['Server', 'Server pinnekjøttet med stuet kålrabi, poteter og gjerne kjøttvæsken som saus.'],
  ],
  'Pitabrød med vegetarfyll': [
    ['Lag de krydrede kikertene', 'Skyll kikertene og tørk dem. Varm olje i en panne og stek dem med tacokrydder til de er varme og litt sprø. Skjær rødløk i tynne skiver og stek den med.'],
    ['Stek søtpotet', 'Skrell søtpotet og skjær den i terninger. Vend dem i olje og salt, og stek dem i ovnen på 200 °C i 20–25 minutter til de er møre.'],
    ['Lag yoghurtdressingen', 'Bland gresk yoghurt med mango chutney. Smak til med salt, pepper og litt limesaft.'],
    ['Skjær mangoen', 'Skrell mangoen og skjær den i terninger.'],
    ['Varm brødene', 'Varm pita- eller lefsebrødene etter anvisningen på pakken.'],
    ['Fyll og server', 'Fyll brødene med kikerter, søtpotet, mango og rødløk. Ha over yoghurtdressingen.'],
  ],
  Plukkfisk: [
    ['Kok poteter', 'Skrell potetene, skjær dem i biter og kok dem møre i lettsaltet vann.'],
    ['Kok fisken', 'Legg torsken i lettkokende vann eller melk i ca. 5 minutter til den er gjennomkokt. Ta den opp og plukk den i biter.'],
    ['Lag melkesausen', 'Smelt smør i en kjele, rør inn litt mel og spe med melk til en jevn saus.'],
    ['Bland', 'Ha fisk og potetbiter i sausen og varm forsiktig gjennom. Bland inn tomatene i biter.'],
    ['Smak til', 'Smak til med salt og pepper.'],
    ['Server', 'Server plukkfisken varm, gjerne med rugbrød.'],
  ],
  'Pulled Pork Asian Style': [
    ['Varm kjøttet', 'Varm pulled pork forsiktig i en kjele eller panne, og tilsett en skvett vann om det trengs så det ikke tørker ut.'],
    ['Lag asiatisk saus', 'Bland en saus av soyasaus, hoisin, litt honning og en skvett lime. Rør den inn i kjøttet.'],
    ['Server', 'Server pulled pork over ris eller nudler, sammen med agurk, vårløk og gulrot.'],
  ],
  'Pulled pork': [
    ['Varm kjøttet', 'Varm pulled pork forsiktig i en kjele eller panne, og tilsett en skvett vann om det trengs så det ikke tørker ut. Følg anvisningen på pakken.'],
    ['Varm brødene', 'Halver hamburgerbrødene og varm dem kort i ovnen eller i en tørr panne.'],
    ['Sett sammen', 'Legg pulled pork i brødene og topp med tilbehøret til pulled pork, for eksempel coleslaw og saus.'],
  ],
  Pølsegrateng: [
    ['Sett ovnen på', 'Sett ovnen på 200 °C.'],
    ['Kok pasta', 'Kok pastaen etter anvisningen på pakken og sil av.'],
    ['Lag hvit saus', 'Smelt smør i en kjele og rør inn melet til det slipper kanten. Tilsett melken litt om gangen under omrøring, og la sausen småkoke i ca. 5 minutter. Smak til med salt og pepper.'],
    ['Gjør klart', 'Skjær pølsen i skiver og hakk vårløken fint.'],
    ['Legg i form', 'Legg pølse, pasta, vårløk og erter i en smurt ildfast form. Hell over sausen og strø over revet ost.'],
    ['Stek', 'Stek i ca. 15 minutter, til osten er gyllen og sausen bobler.'],
    ['Server', 'Server gjerne med salat eller råkost.'],
  ],
  'Pølser i brød': [
    ['Varm pølsene', 'Varm eller stek pølsene etter anvisningen på pakken, til de er gjennomvarme.'],
    ['Varm brødet', 'Varm pølsebrød eller lomper kort i ovnen, i mikroen eller i en tørr panne.'],
    ['Sett sammen', 'Legg pølsen i brødet eller lompa og topp med ketchup, sennep og sprøstekt løk.'],
  ],
  'Quesedilla vegetar': [
    ['Stek soppen tørr', 'Skjær soppen i skiver og stek den tørr i en varm panne til all væsken er borte.'],
    ['Stek fyllet', 'Ha olje, finhakket løk og hvitløk i pannen og stek dem myke. Tilsett røde linser og litt vann, og la dem bli møre. Ha i spinaten til den faller sammen.'],
    ['Krydre', 'Rør inn tacokrydderet helt til slutt.'],
    ['Fyll lefsene', 'Legg fyllet på halve lefsen, og legg ost oppå, gjerne mozzarella. Brett lefsen over.'],
    ['Stek', 'Stek quesadillaen i olje i en panne på middels høy varme, ca. 2 minutter på hver side.'],
    ['Server', 'Skjær i biter og server med guacamole og salsa.'],
  ],
  Raspeballer: [
    ['Lag deigen', 'Riv rå poteter fint og bland dem med litt kokte, moste poteter, mel og salt, til du får en fast deig.'],
    ['Form ballene', 'Form deigen til baller med fuktige hender. Legg gjerne en liten terning saltkjøtt eller flesk i midten.'],
    ['Kok', 'Legg ballene forsiktig i lettkokende, saltet vann og la dem småkoke ca. 45–60 minutter, avhengig av størrelsen.'],
    ['Server', 'Server raspeballene med smør, og gjerne kokt saltkjøtt, kålrabistappe og bacon.'],
  ],
  Reker: [
    ['Ta frem rekene', 'Ta rekene ut av kjøleskapet og la dem renne godt av.'],
    ['Legg på brødet', 'Legg loff eller brødskiver på tallerkenen og smør på majones.'],
    ['Server', 'Legg rekene på brødet og server med sitronbåter til å presse over.'],
  ],
  Ribbe: [
    ['Forbered ribba', 'Ta ribba ut av kjøleskapet i god tid. Ripe svartet, og gni inn salt, pepper og litt fennikelfrø på kjøttsiden. Ha gjerne hvitløk og rosmarin på kjøttsiden.'],
    ['Stek ved lav varme', 'Legg ribba i en stekepanne med svartet ned og hell kokende, saltet vann i bunnen. Stek i ovnen på ca. 170 °C i 1 time, og snu deretter svartet opp.'],
    ['Stek videre', 'Senk temperaturen til ca. 90–110 °C og stek videre i flere timer, til kjernetemperaturen er ca. 85–90 °C. Legg hakkede grønnsaker rundt ribba mot slutten.'],
    ['Gjør svartet sprøtt', 'Øk til 210 °C eller bruk grill helt til slutt til svartet er sprøtt og bobler seg. Følg med så det ikke svir seg.'],
    ['Lag sausen', 'Brun kjøttskraper og grønnsaker i smør, spe med vin eller eplejuice, og kok inn. Tilsett vann og la det småkoke i ca. 2 timer. Sil, bland med stekevæske fra ribba, jevn med brun mel-og-smør-jevning, og smak til med soyasaus, worcestershire og pepper.'],
    ['Lag tilbehøret', 'Kok poteter og varm surkål. Stek medisterkaker og julepølse etter anvisningen på pakken.'],
    ['La ribba hvile og server', 'La ribba hvile ca. 10 minutter før du skjærer den. Server med tilbehør og saus.'],
  ],
  Risengrynsgrøt: [
    ['Lag grøten', 'Følg anvisningen på pakken: kok risengryn i melk under omrøring til grøten er tykk og kremet, ofte ca. 30–40 minutter. Rør ofte så den ikke brenner seg.'],
    ['Smak til', 'Tilsett en klype salt og eventuelt litt mer melk om grøten blir for tykk.'],
    ['Server', 'Server grøten varm med sukker og kanel, og gjerne en klatt smør.'],
  ],
  Risotto: [
    ['Fres løk og hvitløk', 'Finhakk hvitløk og løk. Fres dem myke i olivenolje og litt smør i en stor kjele, uten å brune dem.'],
    ['Stek baconet og kyllingen', 'Stek bacon og kyllingfilet i biter i en panne til de er gylne og gjennomstekt. Sett til side.'],
    ['Rist risen', 'Ha risottoriset i kjelen og rist det litt til det blir gjennomsiktig i kantene. Hell i hvitvin eller eplejuice og rør til det meste er inne.'],
    ['Tilsett kraft', 'Varm kyllingkraften i en kjele. Tilsett den litt om gangen mens du rører, og la risen suge opp væsken mellom hver gang. Det tar ca. 15–20 minutter, til risen er mør men litt fast i midten.'],
    ['Stek soppen', 'Skjær soppen i skiver og stek den gylden i smør.'],
    ['Bland', 'Ta kjelen av varmen og rør inn parmesan og smør. Vend inn sopp, bacon og kylling og la det trekke under lokk i 2 minutter.'],
    ['Server', 'Server risottoen med mer parmesan og gjerne hakket persille.'],
  ],
  Salmalaks: [
    ['Sett ovnen på', 'Sett ovnen på 200 °C.'],
    ['Krydre laksen', 'Legg salmalaksen i en ildfast form. Ha soyasaus over og krydre med litt pepper.'],
    ['Stek laksen', 'Stek i ovnen i ca. 12–15 minutter, til laksen er gjennomstekt.'],
    ['Lag salsaen', 'Skjær mango, avokado, paprika og vårløk i små terninger og bland dem.'],
    ['Varm naanbrødet', 'Varm naanbrødet etter anvisningen på pakken.'],
    ['Server', 'Server laksen med salsa og naanbrød.'],
  ],
  'Shepherds pie': [
    ['Sett ovnen på', 'Sett ovnen på 180 °C.'],
    ['Skjær grønnsaker', 'Finhakk løk og skjær gulrot i små terninger.'],
    ['Brun kjøttet', 'Brun kjøttdeigen av lam i smør til den har skiftet farge. Ta den ut.'],
    ['Lag saus', 'Stek løk og gulrot myke i pannen. Legg kjøttet tilbake og rør inn tomatpuré. Strø over litt mel, rør godt og hell i hønsebuljong. La det småkoke i 15–20 minutter til sausen tykner.'],
    ['Ha i erter og mais', 'Rør inn erter og mais og smak til med salt og pepper.'],
    ['Lag potetmos', 'Kok potetene møre, og mos dem med melk og smør. Smak til med salt, pepper og muskat.'],
    ['Legg i form', 'Legg kjøttblandingen i en ildfast form, dekk med potetmos og strø over revet ost.'],
    ['Stek', 'Stek i ca. 35–40 minutter, til overflaten er gyllen og det bobler i kantene.'],
  ],
  'Skinke- ostepai': [
    ['Lag bunnen', 'Sett ovnen på 180 °C. Lag en paibunn av mel, smør og litt vann, eller bruk ferdig. Gafle bunnen og forstek den i ovnen i 10–15 minutter.'],
    ['Gjør fyllet klart', 'Del brokkolien i små buketter og kok dem 2 minutter. Skjær rødløk i tynne skiver og skinken fra boksen i biter.'],
    ['Legg på fyll', 'Ta bunnen ut og fordel brokkoli, skinke og rødløk utover.'],
    ['Lag eggeblandingen', 'Visp 2–3 egg sammen med melk eller fløte, salt og pepper, og hell det over fyllet.'],
    ['Ost og stek', 'Strø revet ost over og sett pai en tilbake i ovnen. Stek til fyllet er stivnet og overflaten gyllen, ca. 25–30 minutter.'],
  ],
  'Spagetti og kjøttboller': [
    ['Kok spagetti', 'Kok spagettien etter anvisningen på pakken og sil av.'],
    ['Stek kjøttbollene', 'Stek kjøttbollene i en panne til de har fått farge og er gjennomvarme.'],
    ['Varm sausen', 'Varm spagettisausen i en kjele og legg i kjøttbollene. La det småkoke noen minutter.'],
    ['Server', 'Server kjøttbollene og sausen over spagettien, gjerne med revet ost.'],
  ],
  'Spicy scampitaco': [
    ['Lag ferskensalsa', 'Skjær fersken, paprika og løk i små terninger. Bland med limesaft, olivenolje, hakket koriander og salt.'],
    ['Lag avokadokrem', 'Mos avokado og bland den med rømme, limesaft og koriander. Smak til med salt.'],
    ['Lag den sterke rømmen', 'Bland resten av rømmen med hot saus til den er så sterk du vil.'],
    ['Krydre scampien', 'Vend scampien i paprikapulver, spisskummen, salt og litt hvitløkspulver.'],
    ['Stek scampien', 'Stek scampien i olje på middels høy varme, ca. 1 minutt på hver side. Ta den ut.'],
    ['Varm lefsene og server', 'Varm tacolefsene. Legg på avokadokrem, salsa og scampi, og topp med vårløk, koriander, sterk rømme og limebåter.'],
  ],
  'Steam buns': [
    ['Varm kjøttet', 'Varm pulled pork forsiktig i en panne. Tilsett sweet chilli-saus, hoisinsaus og litt limesaft, og la det trekke.'],
    ['Skjær grønnsaker', 'Skjær gulrot og vårløk i tynne staver.'],
    ['Damp buns', 'Damp steam buns etter anvisningen på pakken, vanligvis noen minutter i dampkurv eller over kokende vann, til de er myke og varme.'],
    ['Fyll', 'Åpne bunsen og fyll dem med pulled pork, gulrot og vårløk. Bruk gjerne litt ekstra saus.'],
    ['Server', 'Server med limebåter.'],
  ],
  'Steks laks med blomkålpure': [
    ['Lag blomkålpuréen', 'Del blomkålen i buketter og kok dem møre i lettsaltet vann. Sil av og kjør dem glatte med fløte og litt smør. Smak til med salt og pepper.'],
    ['Stek sjalottløk', 'Skjær sjalottløk i tynne skiver og stek dem gylne i smør.'],
    ['Stek laksen', 'Krydre laksen med salt og pepper og stek den i smør, ca. 4 minutter på hver side, slik at midten fortsatt er saftig. La den hvile litt.'],
    ['Server', 'Legg blomkålpuré på tallerkenen, legg laksen oppå og topp med sjalottløk.'],
  ],
  'Stekt laks med brokkoli og soyasmør': [
    ['Del og krydre laksen', 'Del laksen i fire porsjoner og krydre med salt og pepper.'],
    ['Stek laksen', 'Stek laksen i en panne eller på grillen til den er gylden på begge sider, ca. 4 minutter til sammen.'],
    ['Kok brokkoli', 'Del brokkolien i buketter og kok dem møre i lettsaltet vann. Sil av.'],
    ['Kok ris', 'Kok risen etter anvisningen på pakken.'],
    ['Lag soyasmør', 'Smelt smør i en panne og la finrevet ingefær bli gyllen i det. Tilsett soyasaus.'],
    ['Server', 'Legg laksen på tallerkenen med brokkoli og ris, og hell soyasmøret over.'],
  ],
  'Stekt ris': [
    ['Kok ris', 'Kok risen og la den avkjøles helt, gjerne dagen før. Kald ris blir best.'],
    ['Skjær tilbehør', 'Skjær det du vil ha i stekt ris, for eksempel grønnsaker, egg, skinke eller kylling, i små biter.'],
    ['Stek', 'Varm olje i en stor panne eller wok på høy varme. Stek tilbehøret til det er ferdig og skyv det til siden.'],
    ['Ha i risen', 'Ha risen i pannen og stek den til den er varm og litt sprø. Bland inn tilbehøret.'],
    ['Smak til', 'Smak til med soyasaus og pepper og server med en gang.'],
  ],
  'Svinekam med rotgrønnsaker': [
    ['Sett ovnen på', 'Sett ovnen på 200 °C.'],
    ['Skjær rotgrønnsaker', 'Skrell gulrot, poteter, kålrot og sellerirot, og skjær dem i grove biter. Legg dem i en ildfast form eller på en stekeplate med olje, salt, pepper og litt timian.'],
    ['Krydre svinekammen', 'Gni svinekammen med sennep, salt, pepper og timian.'],
    ['Brun kjøttet', 'Brun kammen raskt på alle sider i en varm panne.'],
    ['Stek', 'Legg kammen oppå grønnsakene og stek i ovnen til kjernetemperaturen er 68–70 °C, ca. 45–60 minutter avhengig av størrelsen.'],
    ['La den hvile', 'La kjøttet hvile 10 minutter under folie før du skjærer det i skiver.'],
    ['Server', 'Server kammen med rotgrønnsakene og pannesaften over.'],
  ],
}

export default steps
