import type { StepList } from './types'

const steps: Record<string, StepList> = {
  Frossenpizza: [
    ['Varm ovnen', 'Sett ovnen på temperaturen som står på pizzaesken, vanligvis 200–225 °C.'],
    ['Stek pizzaen', 'Ta pizzaen ut av emballasjen og legg den rett på risten eller på en plate med bakepapir. Stek i ca. 10–15 minutter, til osten er smeltet og bunnen sprø.'],
    ['Server', 'La pizzaen stå et par minutter og skjær den i biter.'],
  ],
  Fårikål: [
    ['Del kålen', 'Skjær kålhodet i store båter.'],
    ['Legg lagvis', 'Legg kjøttet og kålen lagvis i en stor kjele, med kjøttet med fettsiden ned nederst. Strø salt og hele pepperkorn mellom lagene.'],
    ['Tilsett vann', 'Hell over ca. 3 dl vann.'],
    ['Kok', 'Kok opp, sett på lokk, og la fårikålen småkoke ca. 2,5 timer, til kjøttet er mørt og løsner fra beinet.'],
    ['Server', 'Server fårikålen varm med kokte poteter.'],
  ],
  Grilling: [
    ['Tenn grillen', 'Tenn opp grillen og la den bli ordentlig varm. Kullgrill trenger ca. 30 minutter.'],
    ['Ta frem maten', 'Ta grillmaten ut av kjøleskapet en stund før steking og krydre den etter smak.'],
    ['Grill', 'Grill kjøttet til det er gjennomstekt. Snu underveis, og hold kyllingen og svinekjøttet lenger unna varmen.'],
    ['La det hvile', 'La kjøttet hvile noen minutter før servering.'],
  ],
  Gryterett: [
    ['Skjær og brun', 'Skjær kjøttet i biter og brun det i en stor kjele. Ta det ut.'],
    ['Stek grønnsakene', 'Stek løk og eventuelle grønnsaker i samme kjele til de er myke.'],
    ['Tilsett væske', 'Legg kjøttet tilbake og hell på buljong eller hermetiske tomater så det nesten dekker.'],
    ['La den småkoke', 'La gryten småkoke under lokk til kjøttet er mørt, 45–90 minutter avhengig av kjøttet.'],
    ['Smak til og server', 'Smak til med salt og pepper og server med ris, poteter eller brød.'],
  ],
  Gulrotsuppe: [
    ['Skjær gulrot', 'Skrell og skjær ca. 5 gulrøtter i biter.'],
    ['Stek løk', 'Stek løk i olje i en kjele til den er myk. Tilsett en skvett hvitvinseddik.'],
    ['Tilsett tomatpuré', 'Rør inn to spiseskjeer tomatpuré og la den ristes i et par minutter.'],
    ['Kok buljongen', 'Kok opp 2,5 dl vann med hønsebuljong og hell det i kjelen sammen med gulrotbitene.'],
    ['Kok til gulrøttene er møre', 'La suppen småkoke til gulrøttene er helt møre.'],
    ['Krydre og blend', 'Krydre med kanel og annet krydder du liker. Blend suppen glatt med en stavmikser og tilsett matfløte eller crème fraîche etter ønske.'],
    ['Server', 'Smak til med salt og pepper og server med brød.'],
  ],
  Gyros: [
    ['Lag marinaden', 'Blend løk, hvitløk, oregano, rosmarin og halvparten av olivenoljen til en pasta. Skjær kjøttet i strimler.'],
    ['Stek kjøttet', 'Brun kjøttet i resten av oljen og tilsett marinaden. La det småkoke på lav varme i 35–40 minutter, til kjøttet er mørt og væsken har kokt inn. Smak til med salt og pepper.'],
    ['Lag pommes frites', 'Stek eller frityrstek pommes frites etter anvisningen på pakken.'],
    ['Gjør løken klar', 'Skjær rødløk i tynne ringer, press sitronsaft over og la den stå til den blir myk.'],
    ['Varm brødet', 'Varm pita- eller lefsebrødene etter anvisningen på pakken.'],
    ['Sett sammen', 'Smør tzatziki på brødet, og legg på agurk, rødløk, kjøtt, pommes frites og smuldret fetaost. Rull sammen og server.'],
  ],
  Hamburger: [
    ['Stek burgerne', 'Stek hamburgerne i en varm panne eller på grillen til de er gjennomstekte, ca. 4–5 minutter på hver side. Legg cheddar over det siste minuttet så den smelter.'],
    ['Skjær tilbehøret', 'Skjær tomat i skiver og vask salaten.'],
    ['Varm brødene', 'Halver hamburgerbrødene og varm dem kort i ovnen eller i en tørr panne.'],
    ['Sett sammen', 'Smør hvitløksdressing på brødene, og legg på salat, tomat og hamburger med ost.'],
  ],
  'Hjemmelaget kebab': [
    ['Marinér kjøttet', 'Skjær lammekjøttet i tynne strimler og krydre etter smak med for eksempel salt, pepper, hvitløk og paprikapulver. La det stå en stund.'],
    ['Lag saus og salat', 'Bland majones, ketchup og kefir til en saus. Skjær kål og løk fint.'],
    ['Stek kjøttet', 'Stek kjøttet på høy varme i en stor panne til det er gjennomstekt og har fått litt farge.'],
    ['Varm lefsene', 'Varm tacolefsene i en tørr panne.'],
    ['Server', 'Fyll lefsene med kjøtt, kål, løk og sausen.'],
  ],
  'Hjemmelaget lasagne': [
    ['Lag kjøttsausen', 'Finhakk løk, hvitløk og gulrot og fres dem myke i olje. Tilsett kjøttdeigen og brun den. Rør inn tomatpuré og la den ristes noen minutter.'],
    ['La den koke inn', 'Hell i kjøttbuljong og la sausen småkoke og tykne i ca. 15 minutter. Smak til med salt og pepper.'],
    ['Lag den kremete sausen', 'Varm melken og rør inn eggeplommene av varmen. Bland dette inn i kjøttsausen. Rør inn halvparten av parmesanen.'],
    ['Sett ovnen på', 'Sett ovnen på 180 °C.'],
    ['Legg lagvis', 'Legg kjøttsaus, lasagneplater og mozzarella lagvis i en ildfast form. Avslutt med kjøttsaus, mozzarella og resten av parmesanen.'],
    ['Stek', 'Stek i ca. 30–35 minutter, til lasagnen er gyllen og bobler.'],
    ['La den hvile', 'La lasagnen hvile 10–15 minutter før du skjærer den. Strø over hakket persille.'],
  ],
  'Hjemmelaget pizza med kjøttdeig': [
    ['Sett på ovnen', 'Sett ovnen på høy temperatur, 225–250 °C, og legg inn en plate eller en pizzastein så den blir varm.'],
    ['Stek kjøttdeigen', 'Stek kjøttdeigen i en panne til den er gjennomstekt og smuldrer, og krydre den.'],
    ['Legg pizzabunnen klar', 'Legg pizzabunnen på bakepapir og smør på pizzasaus.'],
    ['Legg på fyll', 'Fordel ost, kjøttdeig, pepperoni og pizzatopping utover.'],
    ['Stek', 'Stek pizzaen i ovnen i 8–12 minutter, til osten er smeltet og gyllenbrun.'],
    ['Server', 'La pizzaen stå et minutt og skjær den i biter.'],
  ],
  'Hjemmelaget sushi': [
    ['Lag eddikblandingen', 'Varm risvinseddik, sukker og salt til alt er oppløst, og la det avkjøles.'],
    ['Kok sushiris', 'Skyll sushirisen flere ganger til vannet er klart, og la den trekke i 30 minutter. Kok den med 3 deler vann til 2 deler ris: kok opp i 3–4 minutter og la den småkoke på lav varme i ca. 15 minutter.'],
    ['Krydre risen', 'Vend den avkjølte eddikblandingen forsiktig inn i risen mens den avkjøles litt.'],
    ['Lag fyllet', 'Skjær laksen i små terninger og bland den med chilimajones, litt sesamolje og finhakket vårløk.'],
    ['Rull', 'Legg plastfilm på en bambusmatte. Legg på et norialark og et tynt lag ris. Strø over sesamfrø og snu, så risen vender ned mot matten. Legg lakseblandingen i en stripe over midten, og rull stramt sammen med matten.'],
    ['Skjær', 'Skjær rullen i 6–8 biter med en skarp kniv som du fukter mellom hvert kutt.'],
    ['Server', 'Server med soyasaus, ingefær og wasabi.'],
  ],
  'Indisk boks tikka': [
    ['Stek kyllingen', 'Skjær kyllingfileten i biter og stek dem i en panne til de har fått farge.'],
    ['Tilsett sausen', 'Hell i tikkasausen fra boksen og kokosmelken. Følg anvisningen på boksen.'],
    ['La det småkoke', 'La kyllingen småkoke i sausen til den er gjennomstekt, ca. 10–15 minutter.'],
    ['Varm naanbrødet', 'Varm naanbrødet i ovnen eller i en tørr panne etter anvisningen på pakken.'],
    ['Server', 'Server kyllingen med naanbrød, og gjerne ris.'],
  ],
  'Indisk kylling i kokoscurry': [
    ['Sett på ris', 'Kok risen etter anvisningen på pakken.'],
    ['Skjær kyllingen', 'Skjær kyllingfileten i store biter.'],
    ['Brun kyllingen', 'Varm olje i en panne og brun kyllingbitene på alle sider. Krydre med salt.'],
    ['Tilsett sausen', 'Hell over den indiske sausen. Rør rundt og la det småkoke i 15–20 minutter, til kyllingen er gjennomstekt.'],
    ['Varm naanbrødet', 'Varm naanbrødet etter anvisningen på pakken.'],
    ['Server', 'Server kyllingen med ris, naanbrød og mango chutney.'],
  ],
  'Japansk boks teryaki': [
    ['Stek kyllingen', 'Skjær kyllingfileten i biter og stek dem i en panne til de har fått farge.'],
    ['Kok brokkolien', 'Del brokkolien i buketter og kok den 2–3 minutter, til den er mør men fortsatt fast.'],
    ['Tilsett teriyakisausen', 'Hell teriyakisausen fra boksen over kyllingen. Følg anvisningen på boksen og la det småkoke til kyllingen er gjennomstekt.'],
    ['Server', 'Server kyllingen med brokkoli, gjerne med ris.'],
  ],
  'Karbonader med rotmos': [
    ['Kok rotgrønnsaker', 'Skrell og skjær poteter, gulrot og kålrot i biter og kok dem møre, ca. 15–20 minutter.'],
    ['Stek løk og purre', 'Stek løk og purre i litt smør til de er myke. Sett til side.'],
    ['Stek karbonadene', 'Stek karbonadene i smør på middels varme, ca. 4 minutter på hver side, til de er gjennomstekte. Hold dem varme i ovnen på 100 °C.'],
    ['Lag moset', 'Sil av grønnsakene og mos dem sammen med halvparten av melken. Tilsett smør og resten av melken litt om gangen til moset er glatt. Smak til med salt og pepper.'],
    ['Bland inn', 'Rør inn den stekte løken og purren, og de frosne ertene. Varm gjennom i ca. 2 minutter.'],
    ['Server', 'Server karbonadene med rotmos, og gjerne litt smeltet smør.'],
  ],
  'Karbonader på brødskiven': [
    ['Stek karbonadene', 'Stek karbonadene i en panne til de er gjennomstekte og gylne.'],
    ['Skjær tilbehøret', 'Vask salaten og legg frem brødskivene.'],
    ['Sett sammen', 'Legg salat og karbonade på brødskiven og legg på ketchup og annet tilbehør du vil ha.'],
  ],
  'Kjøpepizza fra restaurant': [
    ['Bestill eller hent', 'Bestill pizzaen på forhånd, eller hent den på restauranten.'],
    ['Server', 'Ta pizzaen ut av esken og server den varm. Er den blitt kald, kan du varme den noen minutter i ovnen.'],
  ],
  'Kjøpesushi 🍣': [
    ['Bestill eller hent', 'Bestill sushien på forhånd, eller hent den på sushistedet.'],
    ['Sett frem', 'Ta sushien ut av kjøleskapet noen minutter før servering. Sett frem soyasaus, ingefær og wasabi.'],
  ],
  Kjøttkaker: [
    ['Sett på poteter', 'Skrell potetene og sett dem på koking i lettsaltet vann.'],
    ['Lag kjøttmassen', 'Bland kjøttdeigen med salt, pepper og litt krydder etter smak, gjerne med litt mel og melk. Elt massen godt.'],
    ['Form kakene', 'Form massen til flate kjøttkaker med fuktige hender.'],
    ['Stek', 'Stek kakene i smør på middels varme til de er gyllne og gjennomstekte, ca. 5–6 minutter på hver side.'],
    ['Server', 'Server kjøttkakene med kokte poteter, og gjerne brun saus og tilbehør du liker.'],
  ],
  'Koteletter med peppersaus': [
    ['Gjør klart', 'Rens jordskokkene og skjær dem i biter. Skrell sjalottløk og hvitløk, og skjær soppen i skiver.'],
    ['Brun kotelettene', 'Stek kotelettene i olje og smør på middels sterk varme, 2–3 minutter på hver side, til de er gylne. Ta dem ut.'],
    ['Stek grønnsakene', 'Stek jordskokk, sjalottløk og hvitløk i pannen til de har fått farge. Ha i soppen og stek til den er gylden.'],
    ['Lag sausen', 'Skru ned varmen. Hell i oksekraft og la den koke opp, og tilsett kremfløte og pepper. La sausen småkoke til grønnsakene er møre og sausen har tyknet litt.'],
    ['Ferdigstill', 'Legg kotelettene tilbake i pannen og la dem varmes gjennom og bli ferdige i sausen.'],
    ['Server', 'Server med poteter eller bygg.'],
  ],
  'Kremet pasta med falukorv eller pølse': [
    ['Stek pølse og løk', 'Del pølsen i skiver og rødløken i ringer. Stek begge gyllne i smør i en panne.'],
    ['Kok pasta', 'Kok pastaen etter anvisningen på pakken og sil av vannet.'],
    ['Lag sausen', 'Lag carbonarasausen etter anvisningen på pakken.'],
    ['Bland sammen', 'Rør sausen inn i pastaen og legg pølse og løk over.'],
    ['Server', 'Server gjerne med brød og litt parmesan.'],
  ],
  'Kremet pasta med ricotta og purre': [
    ['Kok pasta', 'Kok tagliatellen al dente. Ta vare på ca. 1 dl av kokevannet før du sil av.'],
    ['Stek purren', 'Skjær purren i tynne ringer og stek den myk i olje eller smør, uten at den brunes mye.'],
    ['Lag sausen', 'Rør inn ricotta, revet skall og saft fra sitronen, og litt av kokevannet til du får en kremet saus. Smak til med salt og pepper.'],
    ['Bland', 'Vend pastaen inn i sausen og tilsett mer kokevann om det trengs.'],
    ['Topp og server', 'Server med parmesan, hakkede valnøtter og litt oregano.'],
  ],
}

export default steps
