/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ApiAlgorithmRouteImport } from './routes/api/algorithm'
import { Route as ApiBlueprintLibraryRouteImport } from './routes/api/blueprint-library'
import { Route as ApiBlueprintsRouteImport } from './routes/api/blueprints'
import { Route as ApiFamilyRouteImport } from './routes/api/family'
import { Route as ApiFamilyLeaveRouteImport } from './routes/api/family-leave'
import { Route as ApiFamilyMembersRouteImport } from './routes/api/family-members'
import { Route as ApiIngredientAislesRouteImport } from './routes/api/ingredient-aisles'
import { Route as ApiIngredientsRouteImport } from './routes/api/ingredients'
import { Route as ApiJoinFamilyRouteImport } from './routes/api/join-family'
import { Route as ApiMealPlansRouteImport } from './routes/api/meal-plans'
import { Route as ApiRecipeOverviewRouteImport } from './routes/api/recipe-overview'
import { Route as ApiRecipesRouteImport } from './routes/api/recipes'
import { Route as ApiShoppingListsRouteImport } from './routes/api/shopping-lists'
import { Route as IngredientsIndexRouteImport } from './routes/ingredients/index'
import { Route as RecipesIndexRouteImport } from './routes/recipes/index'
import { Route as RecipesRecipeIdRouteImport } from './routes/recipes/$recipeId'
import { Route as RecipesLibraryRouteImport } from './routes/recipes/library'
import { Route as RecipesNewRouteImport } from './routes/recipes/new'
import { Route as RecipesOverviewRouteImport } from './routes/recipes/overview'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as ShoppingListsIndexRouteImport } from './routes/shopping-lists/index'
import { Route as ShoppingListsListIdRouteImport } from './routes/shopping-lists/$listId'
import { Route as ShoppingListsNewRouteImport } from './routes/shopping-lists/new'
import { Route as AdminBlueprintsIndexRouteImport } from './routes/admin/blueprints/index'
import { Route as AdminBlueprintsBlueprintIdRouteImport } from './routes/admin/blueprints/$blueprintId'
import { Route as AdminBlueprintsNewRouteImport } from './routes/admin/blueprints/new'
import { Route as ApiAdminBlueprintsRouteImport } from './routes/api/admin/blueprints'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiBlueprintImageBlueprintIdRouteImport } from './routes/api/blueprint-image/$blueprintId'
import { Route as ApiBlueprintsAddRouteImport } from './routes/api/blueprints/add'
import { Route as ApiRecipeImageRecipeIdRouteImport } from './routes/api/recipe-image/$recipeId'
import { Route as ApiRecipeRecipeIdRouteImport } from './routes/api/recipe/$recipeId'
import { Route as ApiShoppingListsListIdRouteImport } from './routes/api/shopping-lists/$listId'
import { Route as ApiShoppingListsPreviewRouteImport } from './routes/api/shopping-lists/preview'
import { Route as RecipesRecipeIdCookRouteImport } from './routes/recipes/$recipeId_.cook'
import { Route as ApiAdminBlueprintsBlueprintIdRouteImport } from './routes/api/admin/blueprints/$blueprintId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAlgorithmRoute = ApiAlgorithmRouteImport.update({
  id: '/api/algorithm',
  path: '/api/algorithm',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBlueprintLibraryRoute = ApiBlueprintLibraryRouteImport.update({
  id: '/api/blueprint-library',
  path: '/api/blueprint-library',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBlueprintsRoute = ApiBlueprintsRouteImport.update({
  id: '/api/blueprints',
  path: '/api/blueprints',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFamilyRoute = ApiFamilyRouteImport.update({
  id: '/api/family',
  path: '/api/family',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFamilyLeaveRoute = ApiFamilyLeaveRouteImport.update({
  id: '/api/family-leave',
  path: '/api/family-leave',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFamilyMembersRoute = ApiFamilyMembersRouteImport.update({
  id: '/api/family-members',
  path: '/api/family-members',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIngredientAislesRoute = ApiIngredientAislesRouteImport.update({
  id: '/api/ingredient-aisles',
  path: '/api/ingredient-aisles',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIngredientsRoute = ApiIngredientsRouteImport.update({
  id: '/api/ingredients',
  path: '/api/ingredients',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJoinFamilyRoute = ApiJoinFamilyRouteImport.update({
  id: '/api/join-family',
  path: '/api/join-family',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMealPlansRoute = ApiMealPlansRouteImport.update({
  id: '/api/meal-plans',
  path: '/api/meal-plans',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRecipeOverviewRoute = ApiRecipeOverviewRouteImport.update({
  id: '/api/recipe-overview',
  path: '/api/recipe-overview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRecipesRoute = ApiRecipesRouteImport.update({
  id: '/api/recipes',
  path: '/api/recipes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShoppingListsRoute = ApiShoppingListsRouteImport.update({
  id: '/api/shopping-lists',
  path: '/api/shopping-lists',
  getParentRoute: () => rootRouteImport,
} as any)
const IngredientsIndexRoute = IngredientsIndexRouteImport.update({
  id: '/ingredients/',
  path: '/ingredients/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesIndexRoute = RecipesIndexRouteImport.update({
  id: '/recipes/',
  path: '/recipes/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesRecipeIdRoute = RecipesRecipeIdRouteImport.update({
  id: '/recipes/$recipeId',
  path: '/recipes/$recipeId',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesLibraryRoute = RecipesLibraryRouteImport.update({
  id: '/recipes/library',
  path: '/recipes/library',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesNewRoute = RecipesNewRouteImport.update({
  id: '/recipes/new',
  path: '/recipes/new',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesOverviewRoute = RecipesOverviewRouteImport.update({
  id: '/recipes/overview',
  path: '/recipes/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShoppingListsIndexRoute = ShoppingListsIndexRouteImport.update({
  id: '/shopping-lists/',
  path: '/shopping-lists/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShoppingListsListIdRoute = ShoppingListsListIdRouteImport.update({
  id: '/shopping-lists/$listId',
  path: '/shopping-lists/$listId',
  getParentRoute: () => rootRouteImport,
} as any)
const ShoppingListsNewRoute = ShoppingListsNewRouteImport.update({
  id: '/shopping-lists/new',
  path: '/shopping-lists/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBlueprintsIndexRoute = AdminBlueprintsIndexRouteImport.update({
  id: '/admin/blueprints/',
  path: '/admin/blueprints/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBlueprintsBlueprintIdRoute =
  AdminBlueprintsBlueprintIdRouteImport.update({
    id: '/admin/blueprints/$blueprintId',
    path: '/admin/blueprints/$blueprintId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminBlueprintsNewRoute = AdminBlueprintsNewRouteImport.update({
  id: '/admin/blueprints/new',
  path: '/admin/blueprints/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminBlueprintsRoute = ApiAdminBlueprintsRouteImport.update({
  id: '/api/admin/blueprints',
  path: '/api/admin/blueprints',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBlueprintImageBlueprintIdRoute =
  ApiBlueprintImageBlueprintIdRouteImport.update({
    id: '/api/blueprint-image/$blueprintId',
    path: '/api/blueprint-image/$blueprintId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiBlueprintsAddRoute = ApiBlueprintsAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => ApiBlueprintsRoute,
} as any)
const ApiRecipeImageRecipeIdRoute = ApiRecipeImageRecipeIdRouteImport.update({
  id: '/api/recipe-image/$recipeId',
  path: '/api/recipe-image/$recipeId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRecipeRecipeIdRoute = ApiRecipeRecipeIdRouteImport.update({
  id: '/api/recipe/$recipeId',
  path: '/api/recipe/$recipeId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShoppingListsListIdRoute = ApiShoppingListsListIdRouteImport.update({
  id: '/$listId',
  path: '/$listId',
  getParentRoute: () => ApiShoppingListsRoute,
} as any)
const ApiShoppingListsPreviewRoute = ApiShoppingListsPreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => ApiShoppingListsRoute,
} as any)
const RecipesRecipeIdCookRoute = RecipesRecipeIdCookRouteImport.update({
  id: '/recipes/$recipeId_/cook',
  path: '/recipes/$recipeId/cook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminBlueprintsBlueprintIdRoute =
  ApiAdminBlueprintsBlueprintIdRouteImport.update({
    id: '/$blueprintId',
    path: '/$blueprintId',
    getParentRoute: () => ApiAdminBlueprintsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/algorithm': typeof ApiAlgorithmRoute
  '/api/blueprint-library': typeof ApiBlueprintLibraryRoute
  '/api/blueprints': typeof ApiBlueprintsRouteWithChildren
  '/api/family': typeof ApiFamilyRoute
  '/api/family-leave': typeof ApiFamilyLeaveRoute
  '/api/family-members': typeof ApiFamilyMembersRoute
  '/api/ingredient-aisles': typeof ApiIngredientAislesRoute
  '/api/ingredients': typeof ApiIngredientsRoute
  '/api/join-family': typeof ApiJoinFamilyRoute
  '/api/meal-plans': typeof ApiMealPlansRoute
  '/api/recipe-overview': typeof ApiRecipeOverviewRoute
  '/api/recipes': typeof ApiRecipesRoute
  '/api/shopping-lists': typeof ApiShoppingListsRouteWithChildren
  '/recipes/$recipeId': typeof RecipesRecipeIdRoute
  '/recipes/library': typeof RecipesLibraryRoute
  '/recipes/new': typeof RecipesNewRoute
  '/recipes/overview': typeof RecipesOverviewRoute
  '/shopping-lists/$listId': typeof ShoppingListsListIdRoute
  '/shopping-lists/new': typeof ShoppingListsNewRoute
  '/ingredients/': typeof IngredientsIndexRoute
  '/recipes/': typeof RecipesIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/shopping-lists/': typeof ShoppingListsIndexRoute
  '/admin/blueprints/$blueprintId': typeof AdminBlueprintsBlueprintIdRoute
  '/admin/blueprints/new': typeof AdminBlueprintsNewRoute
  '/api/admin/blueprints': typeof ApiAdminBlueprintsRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/blueprint-image/$blueprintId': typeof ApiBlueprintImageBlueprintIdRoute
  '/api/blueprints/add': typeof ApiBlueprintsAddRoute
  '/api/recipe-image/$recipeId': typeof ApiRecipeImageRecipeIdRoute
  '/api/recipe/$recipeId': typeof ApiRecipeRecipeIdRoute
  '/api/shopping-lists/$listId': typeof ApiShoppingListsListIdRoute
  '/api/shopping-lists/preview': typeof ApiShoppingListsPreviewRoute
  '/recipes/$recipeId/cook': typeof RecipesRecipeIdCookRoute
  '/admin/blueprints/': typeof AdminBlueprintsIndexRoute
  '/api/admin/blueprints/$blueprintId': typeof ApiAdminBlueprintsBlueprintIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/algorithm': typeof ApiAlgorithmRoute
  '/api/blueprint-library': typeof ApiBlueprintLibraryRoute
  '/api/blueprints': typeof ApiBlueprintsRouteWithChildren
  '/api/family': typeof ApiFamilyRoute
  '/api/family-leave': typeof ApiFamilyLeaveRoute
  '/api/family-members': typeof ApiFamilyMembersRoute
  '/api/ingredient-aisles': typeof ApiIngredientAislesRoute
  '/api/ingredients': typeof ApiIngredientsRoute
  '/api/join-family': typeof ApiJoinFamilyRoute
  '/api/meal-plans': typeof ApiMealPlansRoute
  '/api/recipe-overview': typeof ApiRecipeOverviewRoute
  '/api/recipes': typeof ApiRecipesRoute
  '/api/shopping-lists': typeof ApiShoppingListsRouteWithChildren
  '/recipes/$recipeId': typeof RecipesRecipeIdRoute
  '/recipes/library': typeof RecipesLibraryRoute
  '/recipes/new': typeof RecipesNewRoute
  '/recipes/overview': typeof RecipesOverviewRoute
  '/shopping-lists/$listId': typeof ShoppingListsListIdRoute
  '/shopping-lists/new': typeof ShoppingListsNewRoute
  '/ingredients': typeof IngredientsIndexRoute
  '/recipes': typeof RecipesIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/shopping-lists': typeof ShoppingListsIndexRoute
  '/admin/blueprints/$blueprintId': typeof AdminBlueprintsBlueprintIdRoute
  '/admin/blueprints/new': typeof AdminBlueprintsNewRoute
  '/api/admin/blueprints': typeof ApiAdminBlueprintsRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/blueprint-image/$blueprintId': typeof ApiBlueprintImageBlueprintIdRoute
  '/api/blueprints/add': typeof ApiBlueprintsAddRoute
  '/api/recipe-image/$recipeId': typeof ApiRecipeImageRecipeIdRoute
  '/api/recipe/$recipeId': typeof ApiRecipeRecipeIdRoute
  '/api/shopping-lists/$listId': typeof ApiShoppingListsListIdRoute
  '/api/shopping-lists/preview': typeof ApiShoppingListsPreviewRoute
  '/recipes/$recipeId/cook': typeof RecipesRecipeIdCookRoute
  '/admin/blueprints': typeof AdminBlueprintsIndexRoute
  '/api/admin/blueprints/$blueprintId': typeof ApiAdminBlueprintsBlueprintIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/algorithm': typeof ApiAlgorithmRoute
  '/api/blueprint-library': typeof ApiBlueprintLibraryRoute
  '/api/blueprints': typeof ApiBlueprintsRouteWithChildren
  '/api/family': typeof ApiFamilyRoute
  '/api/family-leave': typeof ApiFamilyLeaveRoute
  '/api/family-members': typeof ApiFamilyMembersRoute
  '/api/ingredient-aisles': typeof ApiIngredientAislesRoute
  '/api/ingredients': typeof ApiIngredientsRoute
  '/api/join-family': typeof ApiJoinFamilyRoute
  '/api/meal-plans': typeof ApiMealPlansRoute
  '/api/recipe-overview': typeof ApiRecipeOverviewRoute
  '/api/recipes': typeof ApiRecipesRoute
  '/api/shopping-lists': typeof ApiShoppingListsRouteWithChildren
  '/recipes/$recipeId': typeof RecipesRecipeIdRoute
  '/recipes/library': typeof RecipesLibraryRoute
  '/recipes/new': typeof RecipesNewRoute
  '/recipes/overview': typeof RecipesOverviewRoute
  '/shopping-lists/$listId': typeof ShoppingListsListIdRoute
  '/shopping-lists/new': typeof ShoppingListsNewRoute
  '/ingredients/': typeof IngredientsIndexRoute
  '/recipes/': typeof RecipesIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/shopping-lists/': typeof ShoppingListsIndexRoute
  '/admin/blueprints/$blueprintId': typeof AdminBlueprintsBlueprintIdRoute
  '/admin/blueprints/new': typeof AdminBlueprintsNewRoute
  '/api/admin/blueprints': typeof ApiAdminBlueprintsRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/blueprint-image/$blueprintId': typeof ApiBlueprintImageBlueprintIdRoute
  '/api/blueprints/add': typeof ApiBlueprintsAddRoute
  '/api/recipe-image/$recipeId': typeof ApiRecipeImageRecipeIdRoute
  '/api/recipe/$recipeId': typeof ApiRecipeRecipeIdRoute
  '/api/shopping-lists/$listId': typeof ApiShoppingListsListIdRoute
  '/api/shopping-lists/preview': typeof ApiShoppingListsPreviewRoute
  '/recipes/$recipeId_/cook': typeof RecipesRecipeIdCookRoute
  '/admin/blueprints/': typeof AdminBlueprintsIndexRoute
  '/api/admin/blueprints/$blueprintId': typeof ApiAdminBlueprintsBlueprintIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/api/algorithm'
    | '/api/blueprint-library'
    | '/api/blueprints'
    | '/api/family'
    | '/api/family-leave'
    | '/api/family-members'
    | '/api/ingredient-aisles'
    | '/api/ingredients'
    | '/api/join-family'
    | '/api/meal-plans'
    | '/api/recipe-overview'
    | '/api/recipes'
    | '/api/shopping-lists'
    | '/recipes/$recipeId'
    | '/recipes/library'
    | '/recipes/new'
    | '/recipes/overview'
    | '/shopping-lists/$listId'
    | '/shopping-lists/new'
    | '/ingredients/'
    | '/recipes/'
    | '/settings/'
    | '/shopping-lists/'
    | '/admin/blueprints/$blueprintId'
    | '/admin/blueprints/new'
    | '/api/admin/blueprints'
    | '/api/auth/$'
    | '/api/blueprint-image/$blueprintId'
    | '/api/blueprints/add'
    | '/api/recipe-image/$recipeId'
    | '/api/recipe/$recipeId'
    | '/api/shopping-lists/$listId'
    | '/api/shopping-lists/preview'
    | '/recipes/$recipeId/cook'
    | '/admin/blueprints/'
    | '/api/admin/blueprints/$blueprintId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/api/algorithm'
    | '/api/blueprint-library'
    | '/api/blueprints'
    | '/api/family'
    | '/api/family-leave'
    | '/api/family-members'
    | '/api/ingredient-aisles'
    | '/api/ingredients'
    | '/api/join-family'
    | '/api/meal-plans'
    | '/api/recipe-overview'
    | '/api/recipes'
    | '/api/shopping-lists'
    | '/recipes/$recipeId'
    | '/recipes/library'
    | '/recipes/new'
    | '/recipes/overview'
    | '/shopping-lists/$listId'
    | '/shopping-lists/new'
    | '/ingredients'
    | '/recipes'
    | '/settings'
    | '/shopping-lists'
    | '/admin/blueprints/$blueprintId'
    | '/admin/blueprints/new'
    | '/api/admin/blueprints'
    | '/api/auth/$'
    | '/api/blueprint-image/$blueprintId'
    | '/api/blueprints/add'
    | '/api/recipe-image/$recipeId'
    | '/api/recipe/$recipeId'
    | '/api/shopping-lists/$listId'
    | '/api/shopping-lists/preview'
    | '/recipes/$recipeId/cook'
    | '/admin/blueprints'
    | '/api/admin/blueprints/$blueprintId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/api/algorithm'
    | '/api/blueprint-library'
    | '/api/blueprints'
    | '/api/family'
    | '/api/family-leave'
    | '/api/family-members'
    | '/api/ingredient-aisles'
    | '/api/ingredients'
    | '/api/join-family'
    | '/api/meal-plans'
    | '/api/recipe-overview'
    | '/api/recipes'
    | '/api/shopping-lists'
    | '/recipes/$recipeId'
    | '/recipes/library'
    | '/recipes/new'
    | '/recipes/overview'
    | '/shopping-lists/$listId'
    | '/shopping-lists/new'
    | '/ingredients/'
    | '/recipes/'
    | '/settings/'
    | '/shopping-lists/'
    | '/admin/blueprints/$blueprintId'
    | '/admin/blueprints/new'
    | '/api/admin/blueprints'
    | '/api/auth/$'
    | '/api/blueprint-image/$blueprintId'
    | '/api/blueprints/add'
    | '/api/recipe-image/$recipeId'
    | '/api/recipe/$recipeId'
    | '/api/shopping-lists/$listId'
    | '/api/shopping-lists/preview'
    | '/recipes/$recipeId_/cook'
    | '/admin/blueprints/'
    | '/api/admin/blueprints/$blueprintId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ApiAlgorithmRoute: typeof ApiAlgorithmRoute
  ApiBlueprintLibraryRoute: typeof ApiBlueprintLibraryRoute
  ApiBlueprintsRoute: typeof ApiBlueprintsRouteWithChildren
  ApiFamilyRoute: typeof ApiFamilyRoute
  ApiFamilyLeaveRoute: typeof ApiFamilyLeaveRoute
  ApiFamilyMembersRoute: typeof ApiFamilyMembersRoute
  ApiIngredientAislesRoute: typeof ApiIngredientAislesRoute
  ApiIngredientsRoute: typeof ApiIngredientsRoute
  ApiJoinFamilyRoute: typeof ApiJoinFamilyRoute
  ApiMealPlansRoute: typeof ApiMealPlansRoute
  ApiRecipeOverviewRoute: typeof ApiRecipeOverviewRoute
  ApiRecipesRoute: typeof ApiRecipesRoute
  ApiShoppingListsRoute: typeof ApiShoppingListsRouteWithChildren
  RecipesRecipeIdRoute: typeof RecipesRecipeIdRoute
  RecipesLibraryRoute: typeof RecipesLibraryRoute
  RecipesNewRoute: typeof RecipesNewRoute
  RecipesOverviewRoute: typeof RecipesOverviewRoute
  ShoppingListsListIdRoute: typeof ShoppingListsListIdRoute
  ShoppingListsNewRoute: typeof ShoppingListsNewRoute
  IngredientsIndexRoute: typeof IngredientsIndexRoute
  RecipesIndexRoute: typeof RecipesIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  ShoppingListsIndexRoute: typeof ShoppingListsIndexRoute
  AdminBlueprintsBlueprintIdRoute: typeof AdminBlueprintsBlueprintIdRoute
  AdminBlueprintsNewRoute: typeof AdminBlueprintsNewRoute
  ApiAdminBlueprintsRoute: typeof ApiAdminBlueprintsRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiBlueprintImageBlueprintIdRoute: typeof ApiBlueprintImageBlueprintIdRoute
  ApiRecipeImageRecipeIdRoute: typeof ApiRecipeImageRecipeIdRoute
  ApiRecipeRecipeIdRoute: typeof ApiRecipeRecipeIdRoute
  RecipesRecipeIdCookRoute: typeof RecipesRecipeIdCookRoute
  AdminBlueprintsIndexRoute: typeof AdminBlueprintsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/algorithm': {
      id: '/api/algorithm'
      path: '/api/algorithm'
      fullPath: '/api/algorithm'
      preLoaderRoute: typeof ApiAlgorithmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/blueprint-library': {
      id: '/api/blueprint-library'
      path: '/api/blueprint-library'
      fullPath: '/api/blueprint-library'
      preLoaderRoute: typeof ApiBlueprintLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/blueprints': {
      id: '/api/blueprints'
      path: '/api/blueprints'
      fullPath: '/api/blueprints'
      preLoaderRoute: typeof ApiBlueprintsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/family': {
      id: '/api/family'
      path: '/api/family'
      fullPath: '/api/family'
      preLoaderRoute: typeof ApiFamilyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/family-leave': {
      id: '/api/family-leave'
      path: '/api/family-leave'
      fullPath: '/api/family-leave'
      preLoaderRoute: typeof ApiFamilyLeaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/family-members': {
      id: '/api/family-members'
      path: '/api/family-members'
      fullPath: '/api/family-members'
      preLoaderRoute: typeof ApiFamilyMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ingredient-aisles': {
      id: '/api/ingredient-aisles'
      path: '/api/ingredient-aisles'
      fullPath: '/api/ingredient-aisles'
      preLoaderRoute: typeof ApiIngredientAislesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ingredients': {
      id: '/api/ingredients'
      path: '/api/ingredients'
      fullPath: '/api/ingredients'
      preLoaderRoute: typeof ApiIngredientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/join-family': {
      id: '/api/join-family'
      path: '/api/join-family'
      fullPath: '/api/join-family'
      preLoaderRoute: typeof ApiJoinFamilyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meal-plans': {
      id: '/api/meal-plans'
      path: '/api/meal-plans'
      fullPath: '/api/meal-plans'
      preLoaderRoute: typeof ApiMealPlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/recipe-overview': {
      id: '/api/recipe-overview'
      path: '/api/recipe-overview'
      fullPath: '/api/recipe-overview'
      preLoaderRoute: typeof ApiRecipeOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/recipes': {
      id: '/api/recipes'
      path: '/api/recipes'
      fullPath: '/api/recipes'
      preLoaderRoute: typeof ApiRecipesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shopping-lists': {
      id: '/api/shopping-lists'
      path: '/api/shopping-lists'
      fullPath: '/api/shopping-lists'
      preLoaderRoute: typeof ApiShoppingListsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingredients/': {
      id: '/ingredients/'
      path: '/ingredients'
      fullPath: '/ingredients/'
      preLoaderRoute: typeof IngredientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/': {
      id: '/recipes/'
      path: '/recipes'
      fullPath: '/recipes/'
      preLoaderRoute: typeof RecipesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/$recipeId': {
      id: '/recipes/$recipeId'
      path: '/recipes/$recipeId'
      fullPath: '/recipes/$recipeId'
      preLoaderRoute: typeof RecipesRecipeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/library': {
      id: '/recipes/library'
      path: '/recipes/library'
      fullPath: '/recipes/library'
      preLoaderRoute: typeof RecipesLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/new': {
      id: '/recipes/new'
      path: '/recipes/new'
      fullPath: '/recipes/new'
      preLoaderRoute: typeof RecipesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/overview': {
      id: '/recipes/overview'
      path: '/recipes/overview'
      fullPath: '/recipes/overview'
      preLoaderRoute: typeof RecipesOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shopping-lists/': {
      id: '/shopping-lists/'
      path: '/shopping-lists'
      fullPath: '/shopping-lists/'
      preLoaderRoute: typeof ShoppingListsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shopping-lists/$listId': {
      id: '/shopping-lists/$listId'
      path: '/shopping-lists/$listId'
      fullPath: '/shopping-lists/$listId'
      preLoaderRoute: typeof ShoppingListsListIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shopping-lists/new': {
      id: '/shopping-lists/new'
      path: '/shopping-lists/new'
      fullPath: '/shopping-lists/new'
      preLoaderRoute: typeof ShoppingListsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/blueprints/': {
      id: '/admin/blueprints/'
      path: '/admin/blueprints'
      fullPath: '/admin/blueprints/'
      preLoaderRoute: typeof AdminBlueprintsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/blueprints/$blueprintId': {
      id: '/admin/blueprints/$blueprintId'
      path: '/admin/blueprints/$blueprintId'
      fullPath: '/admin/blueprints/$blueprintId'
      preLoaderRoute: typeof AdminBlueprintsBlueprintIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/blueprints/new': {
      id: '/admin/blueprints/new'
      path: '/admin/blueprints/new'
      fullPath: '/admin/blueprints/new'
      preLoaderRoute: typeof AdminBlueprintsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/blueprints': {
      id: '/api/admin/blueprints'
      path: '/api/admin/blueprints'
      fullPath: '/api/admin/blueprints'
      preLoaderRoute: typeof ApiAdminBlueprintsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/blueprint-image/$blueprintId': {
      id: '/api/blueprint-image/$blueprintId'
      path: '/api/blueprint-image/$blueprintId'
      fullPath: '/api/blueprint-image/$blueprintId'
      preLoaderRoute: typeof ApiBlueprintImageBlueprintIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/blueprints/add': {
      id: '/api/blueprints/add'
      path: '/add'
      fullPath: '/api/blueprints/add'
      preLoaderRoute: typeof ApiBlueprintsAddRouteImport
      parentRoute: typeof ApiBlueprintsRoute
    }
    '/api/recipe-image/$recipeId': {
      id: '/api/recipe-image/$recipeId'
      path: '/api/recipe-image/$recipeId'
      fullPath: '/api/recipe-image/$recipeId'
      preLoaderRoute: typeof ApiRecipeImageRecipeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/recipe/$recipeId': {
      id: '/api/recipe/$recipeId'
      path: '/api/recipe/$recipeId'
      fullPath: '/api/recipe/$recipeId'
      preLoaderRoute: typeof ApiRecipeRecipeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shopping-lists/$listId': {
      id: '/api/shopping-lists/$listId'
      path: '/$listId'
      fullPath: '/api/shopping-lists/$listId'
      preLoaderRoute: typeof ApiShoppingListsListIdRouteImport
      parentRoute: typeof ApiShoppingListsRoute
    }
    '/api/shopping-lists/preview': {
      id: '/api/shopping-lists/preview'
      path: '/preview'
      fullPath: '/api/shopping-lists/preview'
      preLoaderRoute: typeof ApiShoppingListsPreviewRouteImport
      parentRoute: typeof ApiShoppingListsRoute
    }
    '/recipes/$recipeId_/cook': {
      id: '/recipes/$recipeId_/cook'
      path: '/recipes/$recipeId/cook'
      fullPath: '/recipes/$recipeId/cook'
      preLoaderRoute: typeof RecipesRecipeIdCookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/blueprints/$blueprintId': {
      id: '/api/admin/blueprints/$blueprintId'
      path: '/$blueprintId'
      fullPath: '/api/admin/blueprints/$blueprintId'
      preLoaderRoute: typeof ApiAdminBlueprintsBlueprintIdRouteImport
      parentRoute: typeof ApiAdminBlueprintsRoute
    }
  }
}

interface ApiBlueprintsRouteChildren {
  ApiBlueprintsAddRoute: typeof ApiBlueprintsAddRoute
}

const ApiBlueprintsRouteChildren: ApiBlueprintsRouteChildren = {
  ApiBlueprintsAddRoute: ApiBlueprintsAddRoute,
}

const ApiBlueprintsRouteWithChildren = ApiBlueprintsRoute._addFileChildren(
  ApiBlueprintsRouteChildren,
)

interface ApiShoppingListsRouteChildren {
  ApiShoppingListsListIdRoute: typeof ApiShoppingListsListIdRoute
  ApiShoppingListsPreviewRoute: typeof ApiShoppingListsPreviewRoute
}

const ApiShoppingListsRouteChildren: ApiShoppingListsRouteChildren = {
  ApiShoppingListsListIdRoute: ApiShoppingListsListIdRoute,
  ApiShoppingListsPreviewRoute: ApiShoppingListsPreviewRoute,
}

const ApiShoppingListsRouteWithChildren =
  ApiShoppingListsRoute._addFileChildren(ApiShoppingListsRouteChildren)

interface ApiAdminBlueprintsRouteChildren {
  ApiAdminBlueprintsBlueprintIdRoute: typeof ApiAdminBlueprintsBlueprintIdRoute
}

const ApiAdminBlueprintsRouteChildren: ApiAdminBlueprintsRouteChildren = {
  ApiAdminBlueprintsBlueprintIdRoute: ApiAdminBlueprintsBlueprintIdRoute,
}

const ApiAdminBlueprintsRouteWithChildren =
  ApiAdminBlueprintsRoute._addFileChildren(ApiAdminBlueprintsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ApiAlgorithmRoute: ApiAlgorithmRoute,
  ApiBlueprintLibraryRoute: ApiBlueprintLibraryRoute,
  ApiBlueprintsRoute: ApiBlueprintsRouteWithChildren,
  ApiFamilyRoute: ApiFamilyRoute,
  ApiFamilyLeaveRoute: ApiFamilyLeaveRoute,
  ApiFamilyMembersRoute: ApiFamilyMembersRoute,
  ApiIngredientAislesRoute: ApiIngredientAislesRoute,
  ApiIngredientsRoute: ApiIngredientsRoute,
  ApiJoinFamilyRoute: ApiJoinFamilyRoute,
  ApiMealPlansRoute: ApiMealPlansRoute,
  ApiRecipeOverviewRoute: ApiRecipeOverviewRoute,
  ApiRecipesRoute: ApiRecipesRoute,
  ApiShoppingListsRoute: ApiShoppingListsRouteWithChildren,
  RecipesRecipeIdRoute: RecipesRecipeIdRoute,
  RecipesLibraryRoute: RecipesLibraryRoute,
  RecipesNewRoute: RecipesNewRoute,
  RecipesOverviewRoute: RecipesOverviewRoute,
  ShoppingListsListIdRoute: ShoppingListsListIdRoute,
  ShoppingListsNewRoute: ShoppingListsNewRoute,
  IngredientsIndexRoute: IngredientsIndexRoute,
  RecipesIndexRoute: RecipesIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  ShoppingListsIndexRoute: ShoppingListsIndexRoute,
  AdminBlueprintsBlueprintIdRoute: AdminBlueprintsBlueprintIdRoute,
  AdminBlueprintsNewRoute: AdminBlueprintsNewRoute,
  ApiAdminBlueprintsRoute: ApiAdminBlueprintsRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiBlueprintImageBlueprintIdRoute: ApiBlueprintImageBlueprintIdRoute,
  ApiRecipeImageRecipeIdRoute: ApiRecipeImageRecipeIdRoute,
  ApiRecipeRecipeIdRoute: ApiRecipeRecipeIdRoute,
  RecipesRecipeIdCookRoute: RecipesRecipeIdCookRoute,
  AdminBlueprintsIndexRoute: AdminBlueprintsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
