/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ApiAlgorithmRouteImport } from './routes/api/algorithm'
import { Route as ApiFamilyRouteImport } from './routes/api/family'
import { Route as ApiJoinFamilyRouteImport } from './routes/api/join-family'
import { Route as ApiMealPlansRouteImport } from './routes/api/meal-plans'
import { Route as ApiRecipesRouteImport } from './routes/api/recipes'
import { Route as RecipesIndexRouteImport } from './routes/recipes/index'
import { Route as RecipesRecipeIdRouteImport } from './routes/recipes/$recipeId'
import { Route as RecipesNewRouteImport } from './routes/recipes/new'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiRecipeRecipeIdRouteImport } from './routes/api/recipe/$recipeId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAlgorithmRoute = ApiAlgorithmRouteImport.update({
  id: '/api/algorithm',
  path: '/api/algorithm',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFamilyRoute = ApiFamilyRouteImport.update({
  id: '/api/family',
  path: '/api/family',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJoinFamilyRoute = ApiJoinFamilyRouteImport.update({
  id: '/api/join-family',
  path: '/api/join-family',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMealPlansRoute = ApiMealPlansRouteImport.update({
  id: '/api/meal-plans',
  path: '/api/meal-plans',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRecipesRoute = ApiRecipesRouteImport.update({
  id: '/api/recipes',
  path: '/api/recipes',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesIndexRoute = RecipesIndexRouteImport.update({
  id: '/recipes/',
  path: '/recipes/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesRecipeIdRoute = RecipesRecipeIdRouteImport.update({
  id: '/recipes/$recipeId',
  path: '/recipes/$recipeId',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesNewRoute = RecipesNewRouteImport.update({
  id: '/recipes/new',
  path: '/recipes/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRecipeRecipeIdRoute = ApiRecipeRecipeIdRouteImport.update({
  id: '/api/recipe/$recipeId',
  path: '/api/recipe/$recipeId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/algorithm': typeof ApiAlgorithmRoute
  '/api/family': typeof ApiFamilyRoute
  '/api/join-family': typeof ApiJoinFamilyRoute
  '/api/meal-plans': typeof ApiMealPlansRoute
  '/api/recipes': typeof ApiRecipesRoute
  '/recipes/$recipeId': typeof RecipesRecipeIdRoute
  '/recipes/new': typeof RecipesNewRoute
  '/recipes/': typeof RecipesIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/recipe/$recipeId': typeof ApiRecipeRecipeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/algorithm': typeof ApiAlgorithmRoute
  '/api/family': typeof ApiFamilyRoute
  '/api/join-family': typeof ApiJoinFamilyRoute
  '/api/meal-plans': typeof ApiMealPlansRoute
  '/api/recipes': typeof ApiRecipesRoute
  '/recipes/$recipeId': typeof RecipesRecipeIdRoute
  '/recipes/new': typeof RecipesNewRoute
  '/recipes': typeof RecipesIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/recipe/$recipeId': typeof ApiRecipeRecipeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/algorithm': typeof ApiAlgorithmRoute
  '/api/family': typeof ApiFamilyRoute
  '/api/join-family': typeof ApiJoinFamilyRoute
  '/api/meal-plans': typeof ApiMealPlansRoute
  '/api/recipes': typeof ApiRecipesRoute
  '/recipes/$recipeId': typeof RecipesRecipeIdRoute
  '/recipes/new': typeof RecipesNewRoute
  '/recipes/': typeof RecipesIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/recipe/$recipeId': typeof ApiRecipeRecipeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/api/algorithm'
    | '/api/family'
    | '/api/join-family'
    | '/api/meal-plans'
    | '/api/recipes'
    | '/recipes/$recipeId'
    | '/recipes/new'
    | '/recipes/'
    | '/settings/'
    | '/api/auth/$'
    | '/api/recipe/$recipeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/api/algorithm'
    | '/api/family'
    | '/api/join-family'
    | '/api/meal-plans'
    | '/api/recipes'
    | '/recipes/$recipeId'
    | '/recipes/new'
    | '/recipes'
    | '/settings'
    | '/api/auth/$'
    | '/api/recipe/$recipeId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/api/algorithm'
    | '/api/family'
    | '/api/join-family'
    | '/api/meal-plans'
    | '/api/recipes'
    | '/recipes/$recipeId'
    | '/recipes/new'
    | '/recipes/'
    | '/settings/'
    | '/api/auth/$'
    | '/api/recipe/$recipeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ApiAlgorithmRoute: typeof ApiAlgorithmRoute
  ApiFamilyRoute: typeof ApiFamilyRoute
  ApiJoinFamilyRoute: typeof ApiJoinFamilyRoute
  ApiMealPlansRoute: typeof ApiMealPlansRoute
  ApiRecipesRoute: typeof ApiRecipesRoute
  RecipesRecipeIdRoute: typeof RecipesRecipeIdRoute
  RecipesNewRoute: typeof RecipesNewRoute
  RecipesIndexRoute: typeof RecipesIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiRecipeRecipeIdRoute: typeof ApiRecipeRecipeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/algorithm': {
      id: '/api/algorithm'
      path: '/api/algorithm'
      fullPath: '/api/algorithm'
      preLoaderRoute: typeof ApiAlgorithmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/family': {
      id: '/api/family'
      path: '/api/family'
      fullPath: '/api/family'
      preLoaderRoute: typeof ApiFamilyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/join-family': {
      id: '/api/join-family'
      path: '/api/join-family'
      fullPath: '/api/join-family'
      preLoaderRoute: typeof ApiJoinFamilyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meal-plans': {
      id: '/api/meal-plans'
      path: '/api/meal-plans'
      fullPath: '/api/meal-plans'
      preLoaderRoute: typeof ApiMealPlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/recipes': {
      id: '/api/recipes'
      path: '/api/recipes'
      fullPath: '/api/recipes'
      preLoaderRoute: typeof ApiRecipesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/': {
      id: '/recipes/'
      path: '/recipes'
      fullPath: '/recipes/'
      preLoaderRoute: typeof RecipesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/$recipeId': {
      id: '/recipes/$recipeId'
      path: '/recipes/$recipeId'
      fullPath: '/recipes/$recipeId'
      preLoaderRoute: typeof RecipesRecipeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/new': {
      id: '/recipes/new'
      path: '/recipes/new'
      fullPath: '/recipes/new'
      preLoaderRoute: typeof RecipesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/recipe/$recipeId': {
      id: '/api/recipe/$recipeId'
      path: '/api/recipe/$recipeId'
      fullPath: '/api/recipe/$recipeId'
      preLoaderRoute: typeof ApiRecipeRecipeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ApiAlgorithmRoute: ApiAlgorithmRoute,
  ApiFamilyRoute: ApiFamilyRoute,
  ApiJoinFamilyRoute: ApiJoinFamilyRoute,
  ApiMealPlansRoute: ApiMealPlansRoute,
  ApiRecipesRoute: ApiRecipesRoute,
  RecipesRecipeIdRoute: RecipesRecipeIdRoute,
  RecipesNewRoute: RecipesNewRoute,
  RecipesIndexRoute: RecipesIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiRecipeRecipeIdRoute: ApiRecipeRecipeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
